### ISSUE TITLE
Replace quill.js with pell.js

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#103]
Quill.js, as we can see in #20 takes up a huge part of our bundle size, and we are currently only using a small part of it's feature set. Let's go ahead and replace our use of Quill.js in the Learning Dashboard, where we currently store the Notepad, with pell. It should save us 200kb.

Here is the GitHub repository for pell: https://github.com/jaredreich/pell

**Comment by shubhankarb180** [comment]
If this issue is open then can you assign this issue to me ?

**Comment by mikhael28** [comment]
Sounds great @shubhankarb180 - please make sure that the journal is successfully being saved with the onBlur effect, and displaying properly. Please try to make the CSS on the Notepad roughly similar in quality (read: pre-made theme) or better. Pell community might have some pre-made CSS themes ready for us - maybe we can support multiple themes? Just thinking out loud, multiple themes is not a requirement for this Issue.

**Comment by mikhael28** [comment]
@shubhankarb180 when submitting PR, can you also run source-map-explorer to show what the impact on bundle size is? Also, please make sure to test the journal saving functionality, before sending code in for review.

**Comment by shubhankarb180** [comment]
@mikhael28 I have checked the documentation for pell.js and there is neither any onBlur attribute to configure neither we are have any themes as such . We can style the editor using custom sass file. So how to get the onBlur attribute working with pell.js ? Also can you provide a user which I can use to access the learning dashboard as its locked ?

**Comment by mikhael28** [comment]
onBlur is a browser API, with a synthetic event available in React. Theoretically, we could maybe attach onBlur to the parent div that holds pell? Would we have a way of accessing the pell state?

The onBlur activates when an element loses the active focus of the mouse/keyboard, essentially if they click out of the element/parent element. At that point, could we then take the state of the journal and auto-save it? 

Great investigation so far. Is there a way to modify the CSS without SASS? Are the classNames available to modify in the DevTools? If not, we will have to add some SASS support to the dev build process and the production build process, which - is probably a good idea - but let's avoid it if we can. It's extra work, and we have all of our code in regular CSS.

**Comment by mikhael28** [comment]
Don't know if this will be helpful: https://reactjs.org/docs/events.html

**Comment by shubhankarb180** [comment]
The onBlur activates when an element loses the active focus of the mouse/keyboard, essentially if they click out of the element/parent element. At that point, could we then take the state of the journal and auto-save it? _- w.r.t react documentation in theory this should work .. I can test that once .._ 

Great investigation so far. Is there a way to modify the CSS without SASS? Are the classNames available to modify in the DevTools? If not, we will have to add some SASS support to the dev build process and the production build process, which - is probably a good idea - but let's avoid it if we can. It's extra work, and we have all of our code in regular CSS. _- we can play with plain css also by mentioning the custom call or the default class which is provided by pell to change the same . I am attaching the documentation for react-pell below you can have a look at it._ 

@mikhael28 Apart from this how can I get the access to the learning dashboard ? Do I need tweak the paywall model to do that ?

Once I get the access to learning dashboard then only I can integrate the new one.

**Comment by mikhael28** [comment]
Alright great, let me know if the onBlur event gets us what we want - and that sounds good about adding the 'containerClassname' attribute for vanilla css. If you would like to add sass, that's fine, but please fully integrate it into the build and test with 'npm run build' to verify that it builds successfully, and use the 'serve' npm package to test the built bundle on localhost:5000

**Comment by mikhael28** [comment]
@shubhankarb180 how goes it? I just sent a PR updating a lot of NPM modules, and removed `quill` as it had a moderate warning for cross-site-scripting. I would love to add Pell in - how is progress?

**Comment by mikhael28** [comment]
Here is a good example from their documentation: https://github.com/jaredreich/pell/blob/master/examples/react.md
