### ISSUE TITLE
EditProfile `Languages` form as a separate component

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#104]
We want to separate out the forms inside the EditProfile component, to get the file size down to 250 lines or so. Let's separate out the languages form into a separate component, refactor it into a hook, and hold it's business logic there. Additionally, let's add a loading indicator that runs while the API request is running to indicate a network transaction is currently underway.

Checkout into `main`, pull the latest code from the upstream, then create a new branch called `feature/#104`

This ticket is reserved for @antonio-b

**Comment by shubhankarb180** [comment]
is this issue open ?

**Comment by antonio-b** [comment]
@mikhael28 Can you assign me this issue? I will work on it this upcoming weekend. Thanks

**Comment by mikhael28** [comment]
Sounds great!

**Comment by antonio-b** [comment]
@mikhael28 Ok, i have a question. Via research, it mentions that hooks dont work with class components. Are you wanting the Editprofile to be changed to a function component or keep as a class? If you do want to keep as a class, how would I implement a hook into a class component? If I'm off on the theory, I will do more research. Maybe its something I'm missing.

**Comment by mikhael28** [comment]
For now, focus on just the Languages component. Don't worry about changing all of EditProfile for now. You would need to convert that class component into a Functional component, that uses hooks like useState and useEffect - yes.

**Comment by antonio-b** [comment]
@mikhael28  Can i send you what i have so far? I have the Language component separated but having some issues writing the function. some functionality doesn't work at this moment.

**Comment by mikhael28** [comment]
@antonio-b great work! Closing this ticket with your merged PR :D
