### ISSUE TITLE
Pomorodo Series - 1/X

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#105]
This is the first ticket item in the Pomodoro series for @akashshyamdev - it will deal primarily with updating the Pomodoro timer & storing records of the session. Right now, the pomodoro timer only stores timer information in state - we need to migrate that to localStorage, so let's create an item called 'activePomodoro' that is updated whenever we click 'play' to start the next round in the pomodoro. `activePomodoro` is an object, that has three sub-objects called one, two, three, with each of those having a 'start' and 'end' timestamp.

When you click the Play button, update the activePomodoro object's `one` attribute with the starting timestamp. The timer will start (for testing sake, you can shorten the length to 10 seconds or so) and after 10 seconds, trigger an alarm using the `alarm.mp3` file in the `assets` folder. Test in multiple browsers, Safari, Chrome and Firefox for audio compatibility. Then, mark the `end` timestamp in the `one` attribute of the `activePomodoro` object. 

From there, the next step is to hit play for 5 seconds to allow for a 'rest' block, after which is triggered another alarm.mp3. This is done again, 10second-5second, and then again 10-second-15 second (for rest). After this, the pomodoro is considered finished, and we will store it in a localStorage `pomodoros` array and we reset the `activePomodoro` object to it's initial state. 

Create a simple container called `PomoRecords` where we can map over the localStorage pomodoros object and see our records.

Please think through edge cases - for example, what happens if someone leaves the page halfway through a pomodoro? We would need to restart the pomodoro, from the most recent level of the `activePomodoro` object. If we are mounting the app for the first time, we need to check for `activePomodoro` and `pomodoros` existence - if they don't exist, we need to create them - otherwise subsequent business logic may break upon first time load of the application.

**Comment by mikhael28** [comment]
@akashshyamdev any questions or is this enough to get started? You don't need to refactor to hooks right now (unless you want to) - you can focus on getting started with adding in the localStorage driven functionality, while keeping the setInterval based timing for now. In the second stage of this ticket series, we will focus on the Service Worker based time management - not now.

**Comment by akashshyamdev** [comment]
hey @mikhael28,

Two things:
1. The Pomodoro component is commented in the LeftNav component. Any reason?
2. The code instantly breaks as soon as I uncomment the Pomodoro due to a couple of files missing
![Screenshot 2021-09-08 at 14 21 44](https://user-images.githubusercontent.com/56759828/132478256-eec6db2f-6eb0-453f-9cc9-3635fa836f75.png)

**Comment by mikhael28** [comment]
Sure, we can have it in a separate page but we also want to keep it in the leftnav. So, you can create a new route called 'PomodoroDashboard' where you can mount the component and test the timer. Regarding the import errors, you may need to change them to work correctly. All the files are there, however I recently moved the two pomodor files from their own folder into the components folder. So, some imports may need to be reorganized by the files are all there.

**Comment by mikhael28** [comment]
Moving forward, keep in mind that you can do all of your testing inside a new route instead of the Leftnav, but at the end of the day I would like the pomodoro to also work in the left nav. This requirement may change due to UX considerations, so for now go ahead and create a new route and do your work in there.

**Comment by mikhael28** [comment]
The continuous deployment URL for the pomodoro branch is here: https://feature-pomodoro.d2nlf8vt833582.amplifyapp.com

**Comment by mikhael28** [comment]
Hey @akashshyamdev how you doing - any progress here?

**Comment by akashshyamdev** [comment]
@mikhael28 Sorry, I'm too busy right now 😭

**Comment by mikhael28** [comment]
Closing this issue and the other Pomodoro issue @jayeclark - going to write up a separate, new ticket on what Pomodoro functionality we want to have that adds onto the code I merged in earlier today.
