### ISSUE TITLE
Add in TypeScript Support

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#108]
Right now, our codebase can only work with ES6 JavaScript, I would like to add in support for TypeScript moving forward. This being originally bootstrapped on Create React App, I'm not sure of the process to manually add in TS support - would appreciate some guidance/PR's on how to do that.

**Comment by akashshyamdev** [comment]
Basically you want to convert the codebase to typescript? Here's a useful article https://medium.com/opensanca/migrating-from-js-to-ts-cra-b5f679086c5a

**Comment by mikhael28** [comment]
@akashshyamdev fantastic resource for whoever wants to pick-up this ticket in the future, thank you!

**Comment by mikhael28** [comment]
@akashshyamdev @Chris-isCoding I am picking this issue up, per https://github.com/mikhael28/paretOS/discussions/97#discussioncomment-1284077

**Comment by akashshyamdev** [comment]
@mikhael28 are you currently working on this? Or can I take this up? I feel that we can migrate each page at a time. We start with the component like `ArenaProofModal` etc and then move onto the pages.

**Comment by mikhael28** [comment]
@akashshyamdev I've just merged some code into main, providing support for TypeScript compilation! Now we will be able to slowly migrate our codebase in that direction, and have an opportunity to tighten up our data flow!
