### ISSUE TITLE
Mobile Nav Padding Top

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#11]
When we see the mobile/tablet nav at the bottom, it sometimes cuts off by 20 px or so the bottom most view of whatever screen we are on. Screenshot attached as an example!
<img width="731" alt="Screen Shot 2021-08-27 at 1 46 32 PM" src="https://user-images.githubusercontent.com/15205259/131186738-60a54829-2ab6-4622-823b-b523b63aa1c6.png">

**Comment by Youspeakcubic** [comment]
@mikhael28 Hello, I'd love to give a shot at fixing this. Just to make sure are we talking about how on smaller screens the right of the bottom nav cuts off?

**Comment by mikhael28** [comment]
@Youspeakcubic good morning, great to have you here! You have a sharp eye, that is INDEED an issue - on smaller screens, the right of the bottom nav cuts off. Would you please look into that?

The main issue described in the ticket, talks about how the NavBar itself doesn't give the components directly on top of it white-space before it kind of protrudes on top of them. In the screenshot, for example, look at the card that says 'Mikha'el completion 0.55%', the first one. You can see the full card, with the two dropdown, and then the white space below with the circular border. On the second card, you can't see that border - the bottomNav interrupts and sticks over the second grey drop-down. Not possible to scroll down to see the full-card - this is an issue that affects multiple components, so please check any changes with other screens as well.

**Comment by mikhael28** [comment]
I've gone ahead and assigned this ticket to you, let me know how it goes and if there is something I can answer for ya!
