### ISSUE TITLE
Nigerian Pidgin Localization

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#121]
@LeoUCon would you mind taking this on, as you are the subject matter expert here?

Please refer to this old, closed Issue for more details on implementation: https://github.com/mikhael28/paretOS/issues/63

**Comment by LeoUCon** [comment]
Currently having this issue

```
error: src refspec Nigeria-Pidgin-Localization does not match any
error: failed to push some refs to 'https://github.com/mikhael28/paretOS.git'
```

After running this: ` git push origin Nigeria-Pidgin-Localization`

**Comment by LeoUCon** [comment]
![image](https://user-images.githubusercontent.com/47278525/139865156-f482ac96-0e69-408c-987f-ca25ab6cf6f7.png)
I saw this initially then I had to force install npm

**Comment by LeoUCon** [comment]
> Currently having this issue
> 
> ```
> error: src refspec Nigeria-Pidgin-Localization does not match any
> error: failed to push some refs to 'https://github.com/mikhael28/paretOS.git'
> ```
> 
> After running this: ` git push origin Nigeria-Pidgin-Localization`

Moved to a different system, so I guess the reason is that I cloned your repo directly instead of cloning my fork..

**Comment by mikhael28** [comment]
@LeoUCon your PR looks great, yes you do need to use npm sadly. Yarn compatibility is currently broken due to Create-React-App 4.0 sucking, and the es-lint compatibilities issues. Please review the PR notes - it's ready to merge, but you need to remove that yarn.lock file from the commit. After you remove and commit that change, I will merge!

**Comment by mikhael28** [comment]
@leouonline great job adding this localization in! I just merged your PR, and so I am going to close this ticket. How has everything been going in Nigeria in the last few months? Would you be interested in helping create an 'Abuja' city guide, similar to what I have implemented for San Jose Costa Rica, in the Library of Context?

**Comment by leouonline** [comment]
@mikhael28 that will be fantastic, can I get a link to the Library of Context, to check out the one for  San Jose Costa Rica?

**Comment by mikhael28** [comment]
@leouonline check this out: https://www.paret0.com/hubs/costaRica you don't even have to 'log in' to the Pareto account, I made the library of context publicly visible for people.

**Comment by mikhael28** [comment]
I have a list of meetups, venture capital, cool companies, etc - basically, if you were born tomorrow and wanted to know what the tech scene in San Jose was like - this would theoretically give you all the information you need! you can also submit items by clicking on that blue document + button, and submit the resource. However, right now I am only able to confirm the resource and 'check it in' to the production dataset through the CMS portal. 
![Screen Shot 2022-03-11 at 11 50 24 AM](https://user-images.githubusercontent.com/15205259/157948332-12ac58bd-1870-4831-9fc8-6f8713e8c6cf.png)

**Comment by mikhael28** [comment]
We would need to have a public 'admin portal' where 'admins' for that particular page, so you would be the Abuja admin, can 'approve' items, and/or we can have the community vote on what they want to add/delete, especially if a resource becomes out of data/the website/article goes down/is removed.

**Comment by mikhael28** [comment]
What are your thoughts?

**Comment by leouonline** [comment]
Interesting the weblinks are great but I was thinking videos will be fantastic.

While for the admin, that's a nice idea. Distributing the managerial task is important

I think we can start with the region first "West Africa" and perhaps when we have more hands we can streamline further.

The platform UI isn't looking modern any plans for that.

**Comment by mikhael28** [comment]
That sounds good, let's start with the 'West Africa' region. I can spin up the page for that, will update you when that's ready.

Re the platform UI - I agree, it needs some work. Do you have any recommendations on where we can start? Is there perhaps a platform somewhere that you think we can draw inspiration from?

**Comment by mikhael28** [comment]
One of the things to keep in mind is having great support for the mobile, and desktop experience. Thinking about West Africa, I would imaging a lot of our users primary device is their phone. Any particularly compelling mobile UI's you've seen lately? 

Right now, @vmcodes is in the process of migrating our Material UI from v4 to 5 - once that's done, we will be centralizing the theming for the platform. We will be replacing the forms across the website using `react-hook-form` and the styles of Material UI - you can take a look at `Login.js` and the login screen in general to see what that looks like.

**Comment by vmcodes** [comment]
@mikhael28 @leouonline Modernizing things sounds great and eventually creating a central Material UI theme will make it possible to have a dark mode as mentioned in #133 . Looking forward towards working together and getting a little more granular with the UI when the time comes.

**Comment by mikhael28** [comment]
Hey @leouonline I sent you an email to your gmail account with a link to join our 'contributor-only' Discord channel so that we can continue the conversation. Let me know if you didn't see it - I sent it to the email listed on your GitHub profile. Closing this issue, as the language has been added to the repository :D

**Comment by leouonline** [comment]
> That sounds good, let's start with the 'West Africa' region. I can spin up the page for that, will update you when that's ready.
> 
> Re the platform UI - I agree, it needs some work. Do you have any recommendations on where we can start? Is there perhaps a platform somewhere that you think we can draw inspiration from?


Awesome here are some places for inspo;

- https://www.behance.net/
- https://dribbble.com/
- https://www.awwwards.com/
- https://pagecollective.com/?ref=screenlane
- https://land-book.com/

**Comment by leouonline** [comment]
> One of the things to keep in mind is having great support for the mobile, and desktop experience. Thinking about West Africa, I would imaging a lot of our users primary device is their phone. Any particularly compelling mobile UI's you've seen lately?
> 
> Right now, @vmcodes is in the process of migrating our Material UI from v4 to 5 - once that's done, we will be centralizing the theming for the platform. We will be replacing the forms across the website using `react-hook-form` and the styles of Material UI - you can take a look at `Login.js` and the login screen in general to see what that looks like.

Definitely responsive is very important.
