### ISSUE TITLE
Logout route / Loading Screen reset

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#122]
To aid debugging in the case of an infinite loading screen in production, let's do two things.

1. Let's create a simple route with React Router called `/logout`which when accessed, resets the application state to initial levels (by using `localStorage.clear()` and `Amplify.logout()`, logs out with Amplify and clears localStorage, then redirects to home `props.history.push('/').
2. On the loading screen, set a timer for 20 seconds - if the initial fetch has not yet finished in that time, let's show a button below the quote that then takes you to the logout route. This will allow us to debug, in case of an initial loading screen bug similar to that which @nikhil12377 recently reported. Basically, this is an escape hatch in development/production where the user can reset their entire application state, to login and start over again.

**Comment by kamilszmajdzinski** [comment]
Hey @mikhael28, can you assign me to this one?

**Comment by kamilszmajdzinski** [comment]
@mikhael28 can you give me push permissions?

**Comment by Emiliano-Russo** [comment]
was this issue resolved? i can do it

**Comment by mikhael28** [comment]
@kamilszmajdzinski are you still planning on working on this? I can assign it to @Emiliano-Russo

**Comment by Emiliano-Russo** [comment]
srry i cant!

**Comment by rkoleci** [comment]
i will give this one a try.

**Comment by mikhael28** [comment]
@Emiliano-Russo all good - I will assign to @rkoleci

**Comment by mikhael28** [comment]
@rkoleci I updated the description of the ticket a little bit, can you read through it and let me know what parts you would like me to expand upon? Essentially, the loading screen can sometimes 'hang', meaning for whatever reason, the application state got messed up and the loading screen is stuck permanently. We want to give our users/devs an escape hatch, to reset the dev environment/localstorage/cognito auth token.

**Comment by rkoleci** [comment]
Still not entirely clear about this.

So far: I created a Logout route to clear/logout.
on Loading screen I show a button after 20s, which redirects to /logout.

Let me know if I'm on the right path.

**Comment by mikhael28** [comment]
@rkoleci yep, that's exactly right! If that's what you have, send in the PR :) Sorry for the delay, hope you had a happy holidays and you are starting your New Year off strong!

**Comment by mikhael28** [comment]
@rkoleci I'm taking your name off the assignment for this ticket, as you haven't responded with a PR. Does anyone else want to take this on?

**Comment by RAnis2017** [comment]
@mikhael28 I'd like to give it a try. Please assign me.

**Comment by mikhael28** [comment]
@RAnis2017 I'm assigning you! Thank you for taking this on! I'm also going to invite you to our contributor only Discord, since you have already had one pull-request accepted and merged into the codebase :)

**Comment by mikhael28** [comment]
@RAnis2017 I see some progress made here - are you ready for a PR review?

**Comment by RAnis2017** [comment]
@mikhael28 Hi, yeah it should be done. However, couldn't get around to testing it thoroughly and I got busy with other stuff. Will try to test tomorrow

**Comment by mikhael28** [comment]
@RAnis2017 I'm unnassigning you as I haven't heard back from you... or maybe you sent in a PR that got merged in, and I forgot about it. Are you interested in working on any other items?

**Comment by mikhael28** [comment]
I took a few minutes to implement this! For anyone wondering, this is what the code looks like - that, and adding this component into the `Routes.tsx` react-router config.
```
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Auth } from '@aws-amplify/auth'

export default function Logout() {
	const navigate = useNavigate();

	async function logout() {
		await Auth.signOut();
		navigate('/');
		window.location.reload();
	}

	useEffect(() => {
		if (window.location.pathname === '/logout') {
			logout();
		}
	}, [])
	return (
		<div></div>
	)
}
```

**Comment by mikhael28** [comment]
Closing!
