### ISSUE TITLE
PWA Offline Fallback Page

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#124]
In the event that the PWA goes offline, we want to provide a custom offline fallback page, as Google recommends per the PWA standard. Let's have something simple, and implement the basic event handlers and offline.html as recommended in this documentation: full code here: https://web.dev/offline-fallback-page/

**Comment by rkoleci** [comment]
I can implement this.

Assign it to me, please.

**Comment by mikhael28** [comment]
@rkoleci would you like to work on this or the Routing Redirect page?

**Comment by rkoleci** [comment]
Both. Lets get familiar with this one first.

**Comment by rkoleci** [comment]
> @rkoleci would you like to work on this or the Routing Redirect page?

Let me know about the redirect issue @mikhael28

**Comment by mikhael28** [comment]
@rkoleci I would probably start on the routing redirect page first - a bit simpler to get started, adding in the PWA offline fallback page introduces potential changes to the build process/npm packages. Do you have any questions about that ticket?

**Comment by mikhael28** [comment]
I've made good progress in putting this together - will be integrated next time I merge code in, along with other Service Worker related things.
