### ISSUE TITLE
Bug: Daily Achievement Proof does not upload to S3 Bucket - "Error: Region is missing"

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#140]
### Description

When a user attempts to submit proof of a daily achievement, they receive an alert that "region is missing" and are unable to upload photo evidence of their proof.  
  
<img width="1148" alt="Screen Shot 2022-03-18 at 3 49 50 PM" src="https://user-images.githubusercontent.com/84106309/159075777-4993942b-05b3-446e-863f-57873a064cdd.png">
  
This appears to be related to missing or incorrect settings in the Storage.put() method of the [uploadToS3](https://github.com/mikhael28/paretOS/blob/main/src/libs/s3.js) function. 

### Steps to Reproduce

1. Navigate to or create an active sprint 
2. Click the "submit work" button on one of the Daily Achievements
3. Select an image file to upload as 'proof' of completing the achievement
4. Dismiss any error notifications and click "Submit Proof"

### Expected behavior:

When the user selects an image file, they should receive a toast notification indicating that the image uploaded successfully. After clicking "submit proof", the achievement should then be visible under "Finished Achievements" and clicking on "Press to See Proof" should allow the user to view the proof that they submitted.
<img width="1143" alt="Screen Shot 2022-03-18 at 4 44 22 PM" src="https://user-images.githubusercontent.com/84106309/159081270-b6688fdd-d456-41d4-a95f-a944647e8885.png">

### Actual behavior
The user receives an error notice that "Region is missing." They are able to click the "Submit Proof" button and their achievement appears under "Finished Achievements", but the achievement indicates that no proof was submitted.
<img width="619" alt="Screen Shot 2022-03-18 at 4 34 51 PM" src="https://user-images.githubusercontent.com/84106309/159081644-b963219e-86fd-4a07-8de7-011983fc017c.png">

### Reproduces how often

100% 

### Additional Information

You might encounter additional S3- and Amplify-related errors/bugs in the 'Submit proof' workflow after resolving this issue. However, for this PR it will be sufficient just to resolve the "Region missing" error, we can address any other bugs later in separate issues!

**Comment by mikhael28** [comment]
@jayeclark pinning this issue - great example of how to write a world-class ticket!
