### ISSUE TITLE
Chore: Fix browser console errors (multiple PRs accepted)

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#142]
## Description

There are a handful errors & warnings logged to the browser console on startup and reload, that can make it difficult for new contributors to distinguish errors introduced by their code changes from pre-existing errors. They are all fairly minor issues, so let's clean them up so it's easier to recognize when new console errors arise!    
 
**Errors**   
   
- [X] React does not recognize the 'disableBackdropClick' prop on a DOM element (error happens on App.js, ExperienceModule.js, and LearnDashboard.js)
- [X] Encountered two children with the same key, '1.4'
- [X] Received 'true' for a non-boolean attribute 'exact'
   
**Warnings**
- [x] componentWillMount has been renamed and is not recommended for use (seems to relate to a dependency, maybe an upgrade will fix it?)
- [x] componentWillReceiveProps has been renamed, and is not recommended for use (seems to relate to a dependency, maybe an upgrade will fix it?)
- [x] componentWillUpdate has been renamed, and is not recommended for use (seems to relate to a dependency, maybe an upgrade will fix it?)
- [x] Using the Sanity client without specifying an API version is deprecated. 
- [x] You have configured Sanity client to use a token in the browser. This may cause unintentional security issues.

## Steps to Reproduce

1. Clone, install and run the project
2. Launch the development server
3. Check the browser console and review the long list of errors
   
   
**Expected behavior:**   
Browser should be free of errors relating to the codebase
    
**Actual behavior:**    
Several errors show in the console

**Reproduces how often:** 100%

## Additional Information

Stacktraces are attached below for reference. (They'll be removed as the errors & warnings are corrected.)
   
<img width="646" alt="Screen Shot 2022-03-20 at 12 16 47 PM" src="https://user-images.githubusercontent.com/84106309/159172323-447a4bdc-628e-400a-adb8-dd13163e7eb1.png">
   
<img width="641" alt="Screen Shot 2022-03-20 at 12 16 55 PM" src="https://user-images.githubusercontent.com/84106309/159172322-c1cdbd54-7852-48aa-8e88-0a27d9d595e0.png">
   
<img width="646" alt="Screen Shot 2022-03-20 at 12 17 03 PM" src="https://user-images.githubusercontent.com/84106309/159172321-5847fcde-ec84-4a82-ad2f-a4ba1c127dcb.png">

**Comment by asko1** [comment]
For the warning about having configured Sanity client to use a token in the browser:

Since it is already publicly available in this repo, I assume I can safely edit the config file to ignore this warning?

**Comment by jayeclark** [comment]
@asko1 Yes, I think that should be fine!

**Comment by mikhael28** [comment]
Heh heh didn't mean to close this issue, GitHub automatically did that! Now, the issues left are the `componentDidUpdate` etc deprecated lifecycle warnings. Those are kind of sporadic and tied to different things. The componentDidUpdate, I believe, is tied to either the DropDown component in the LeftNav (that should be replaced) or the the React Bootstrap modals that are being replaced. In general, we are slowly migrating everything to React-Hooks - so these warnings will slowly be removed, especially as we upgrade the version numbers of our npm modules/remove unsupported ones such as `react-bootstrap`.

**Comment by mikhael28** [comment]
This ticket can be closed because @annovo ’s work replacing the DropDown component has removed these error messages! Well done everyone! @asko1
