### ISSUE TITLE
Improve unit tests for Leaderboard component

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#150]
Are you learning or practicing how to write unit tests for React components, looking to get some portfolio PRs for your job search, or just a wiz at testing who likes to help out Open Source projects? Please consider helping to improve the testing coverage for this project!

## Description
Some basic unit tests have been written for the Leaderboard component, but they need to be fleshed out in order to be able to catch errors introduced into the code in future refactors and enhancements. As you'll see, testing is very light across the entire project right now, but hopefully focusing on doing unit tests 'right' for a handful of components can help provide an easy template for future contributors to apply on the rest of the project.

## Expected Behavior
The Leaderboard is a simple component that takes four props: an array of users that are participating in a particular sprint competition, a number of users to display per page, the current user, and the current user's router history.

On initial render, it shows a table of users sorted in descending order by score. The page that is visible initially is whichever page the current user is on, and the row with the current user is highlighted. (So, if I'm in last place on a leaderboard where there are 3 pages of users, the third page would be displayed first.)

It also shows a podium with the top three scorers on it. (The podium only appears if at least one person in the competition has a score > 0 ... if no one has any scores yet, there is no leader.)
![leaderboard](https://user-images.githubusercontent.com/84106309/159545530-2ea58137-5c57-4409-917e-56de593afc95.gif)

## Finding the Component in the App
1. Fork the repository and follow contributing guidelines to get your local dev environment set up
2. Log in to Pareto, navigate to the arena, and create a sprint starting this past Monday, with yourself and several other test users
3. Once you've created the sprint, view the sprint, click on the 'compete' page, and record that you've completed a few daily achievements (you may need to use the time travel options if you create the spring 
5. When you navigate to the Leaderboard tab, you should see a leaderboard & podium, with yourself in first place.

## Suggested Tests
Currently there are only a few basic tests written - whether the leaderboard table appears with the right number of rows, whether the podium appears, and whether the page that initially shows is the one that the current user is on. Lots of room for improvement!

Some possible tests:   
   
**LEADERBOARD TABLE**
- "correctly increments and decrements pages"
- "initially displays the leaderboard table in descending score order"
- "reacts to a click on the "name" column header by sorting the initial state leaderboard table by descending name order"
- "reacts to a click on "score" column header by sorting the initial state leaderboard table by ascending score order"
-  "reacts to a click on the "rank" column header by sorting the initial state leaderboard by ascending score order"
- "reacts intelligently to new sortby properties. if descending score order is also descending name order, clicking the 'name' 
-  "correctly filters the user array based on a given filter phrase."
- "filters according to a combination of first name plus the first letter of last name. ('John S.' would fit the filter 's'.)"
   
   
**LEADERBOARD PODIUM**
- "displays 3 different podiums of varying heights"
- "displays the number 1 scoring user on the tallest podium"
- "displays the number 3 scoring user on the shorted podium"
- "does not display the podiums no user has a score greater than 0

**Comment by neilgebhard** [comment]
Hi @jayeclark, I seem to have some trouble getting set up. I made an account and logged in successfully. 

However, I can't create a sprint. When I navigate to "Start a Sprint", "Choose Your Sprint Template" and "Choose Your Competitors" are both disabled. Also, the button on that page is stuck on "Saving..." with a loading spinner.

<img width="1440" alt="Screen Shot 2022-04-02 at 7 23 57 PM" src="https://user-images.githubusercontent.com/3175429/161376861-589d03db-476b-4e12-9a33-d96aa67c970f.png">

I tried creating a Sprint Template in the Sprint Template page, but it doesn't seem to create one for me.

<img width="1440" alt="Screen Shot 2022-04-02 at 7 24 18 PM" src="https://user-images.githubusercontent.com/3175429/161376862-88a854d1-02b4-4842-a1c0-5d5f7ed100ce.png">

I'm also getting a ton of errors in the console.

<img width="780" alt="Screen Shot 2022-04-02 at 7 24 54 PM" src="https://user-images.githubusercontent.com/3175429/161376831-e9ecea6e-8b9e-4cdf-9d4c-5c8fb60a97b0.png">

<img width="781" alt="Screen Shot 2022-04-02 at 7 25 08 PM" src="https://user-images.githubusercontent.com/3175429/161376835-c3e02312-f061-44e6-89e5-d43387669427.png">

Am I doing something wrong? I was able to make some tests by examining the code but it would be nice for me to make an actual leaderboard table and interact with the UI.

Also, there are many times when I get stuck on this loading screen while logging into the app. I'd have to clear my browser storage and refresh the page to fix it.

<img width="896" alt="Screen Shot 2022-04-02 at 7 30 29 PM" src="https://user-images.githubusercontent.com/3175429/161377065-9970e239-a363-4410-844d-54d375d857fa.png">

**Comment by jayeclark** [comment]
Thanks for reporting this! I’ll make a fresh account & try to see if I can replicate. Almost certainly you aren’t doing anything wrong, the project just had a major bug addressed (there was a problem where thousands of active sessions were being created every time someone made a sprint) and I’m guessing fixing that might have exposed another issue. 

Just to be sure, you could try double checking that your fork isn’t behind the upstream (the bug fix I mentioned affects the back end, so it could definitely lead to the error you’re seeing if it’s not yet incorporated into your fork.)

If your fork is up to date with the upstream repo & you’re still having this issue, if you reach out to me at jay@jayeclark.dev I can send you the credentials for a test account that is already set up & should allow you to immediately get past these errors while I troubleshoot!

**Comment by neilgebhard** [comment]
Yes, I believe I'm up to date.

<img width="1024" alt="Screen Shot 2022-04-02 at 10 41 36 PM" src="https://user-images.githubusercontent.com/3175429/161384013-08918275-1105-49c8-b9ef-f534d524b361.png">

I'll send you an email to connect.

**Comment by neilgebhard** [comment]
Hi @jayeclark, sorry to be taking so long making the tests. I seem to be having some issues.

I followed some of your testing suggestions, but I can't seem 
First, would it be possible to add points to the competitors in the leaderboard table in the test account? Some of the tests deal with sorting by score so it would be helpful to see how the UI behaves with data.

**Comment by mikhael28** [comment]
Hehe yeah, we had a major bug. Should be good now!

**Comment by mikhael28** [comment]
Closing! Great work @neilgebhard
