### ISSUE TITLE
Bug: Learn dashboard shows "My Mentors" even when you have no mentors

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#155]
## Description

In the Full-Stack JS learning dashboard, there is a section of content titled "My Mentors". The header "My Mentors" appears even if the user does not yet have a mentor.

## Steps to Reproduce

1. After setting up the project on your local machine, click on Full Stack JS.
2. Click through to 'pay', then unlock the experience module (on the pay screen, click on the "no donation" link in the lower left)
3. You should now see the dashboard

### Expected behavior

"My Mentors" should only appear if the user has mentors assigned.

### Actual behavior

"My Mentors" appears even if you have no mentors yet

### Reproduces how often:

Always

## Screenshots
<img width="1030" alt="Screen Shot 2022-03-28 at 1 47 22 PM" src="https://user-images.githubusercontent.com/84106309/160456993-d9ce4f4c-7f7c-4e94-a539-b8acf4c69a41.png">

**Comment by akshathphillips** [comment]
Hello! I'd like to work on this.

**Comment by Olaleye-Blessing** [comment]
Can I work on this? If yes, Do I need to set up [AWS Lambda](https://aws.amazon.com/lambda/) - Serverless first
, MongoDB + other services as found in [built with](https://github.com/mikhael28/paretOS#built-with) section of read.me?

**Comment by jayeclark** [comment]
Hey @Olaleye-Blessing , thanks for your interest in contributing! To answer your question - no, you don't need to worry about AWS Lambda or MongoDB. To set up your local dev environment for this project you should only need to follow the standard `fork → clone → npm install → npm start` process.

@akshathphillips has already claimed this particular issue, but #158 is very similar. (Almost exactly the same issue.) Any chance you'd be interested in helping with that one?

**Comment by Olaleye-Blessing** [comment]
Ok thanks, I'll work on that.

**Comment by mikhael28** [comment]
@akshathphillips any questions on your end? Make sure to pull from the upstream `main` to get the latest bug fixes - I accidentally left a bug in for a bit too long that low-key disabled all buttons 😭 you should be unblocked now

**Comment by akshathphillips** [comment]
No questions on my end. I expect to make progress on this, this weekend. Thanks!

**Comment by MidnightChems** [comment]
Hello,
I think I may have a working fix. Are we able to assign my account a mentor so I can test if the text comes back?
Thanks,

**Comment by MidnightChems** [comment]
Hey,

Just submitted a pull request for this issue. I don't think I have a way to add a mentor to my account to test fully. Let me know if there's any issues and I'll take another look.

**Comment by MidnightChems** [comment]
Updated PR #238

**Comment by mikhael28** [comment]
I want to say this is done - thank you @MidnightChems ! Have I invited you to our contributor only discord yet? If you would like to join, please leave your email here.

**Comment by MidnightChems** [comment]
I would love to join! Please send me an invite at gorazem@outlook.com

**Comment by mikhael28** [comment]
Sent you an invite @MidnightChems
