### ISSUE TITLE
Refactor: Sprint component is very long and could benefit from refactoring

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#157]
## Description
The component `arena/Sprint.js` has a whopping 556 lines of code! Looking through, a good amount of it appears to be repetitive code that could be refactored or broken out into subcomponents.

## Goals
- [ ] Reduce the total lines of code
- [ ] Reduce the amount of repetitive code
- [ ] Improve code efficiency and readability
- [ ] Simplify state management for states that are always all updated at the same time
- [ ] Add comments as necessary to help orient new contributors navigating the file for the first time.

**Comment by Olaleye-Blessing** [comment]
Can I work on this?

**Comment by mikhael28** [comment]
Well done @Olaleye-Blessing - closing this issue!
