### ISSUE TITLE
Bug: Arena sprint view shows "Finished Achievements" and "Daily Achievements" even when there is no content

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#158]
## Description

In the Arena sprint view, there are sections of content titled "Daily Achievements" and "Finished Achievements". These headers appear even if there are no Daily Achievements left to complete and no Finished Achievements completed.

## Steps to Reproduce

1. After setting up the project on your local machine, click on Arena.
2. Create a sprint with two people, using any of the templates
3. Click on the sprint card to view the full sprint

### Expected behavior

"Finished Achievements" section should display the message "You have not reported any achievements yet today." under the section header (in lieu of the achievement cards that would be there) if there are no finished achievements.

"Daily Achievements" section should display the message "You have completed all the available achievements for today." under the section header (in lieu of the achievement cards that would be there) if there are no more daily achievements to complete.

### Actual behavior

The headings appear with no associated content and it creates confusion for the user.

### Reproduces how often:

Always

## Screenshots
<img width="1533" alt="Screen Shot 2022-03-30 at 10 44 38 AM" src="https://user-images.githubusercontent.com/84106309/160862627-2ed274eb-0a89-448d-9212-64e98bcc24c4.png">
<img width="1533" alt="Screen Shot 2022-03-30 at 10 44 14 AM" src="https://user-images.githubusercontent.com/84106309/160862639-28a752f5-012e-4f45-ab39-4d1f02338391.png">

**Comment by Olaleye-Blessing** [comment]
You said I should use NPM according to [your comment](https://github.com/mikhael28/paretOS/issues/155#issuecomment-1083245920). Isn't it supposed to be **yarn**?

**Comment by jayeclark** [comment]
Yes, apologies for that - I sometimes accidentally write `npm` from muscle memory. You’re correct, yarn is the package manager this repo uses. 😂

**Comment by Olaleye-Blessing** [comment]
I've run NPM already, is there a way to correct this?

**Comment by jayeclark** [comment]
Yes, it’s a quick fix! Delete the `package-lock.json` that npm created, and the node_modules directory that it created, and run `yarn install`.

**Comment by Olaleye-Blessing** [comment]
Nice one @jayeclark @mikhael28 

I've been here for some time now, I don't know what the issue could be.

![Screenshot (263)](https://user-images.githubusercontent.com/70102539/161219623-7877b965-cc30-44f1-bb04-dc05b5650958.png)

![Screenshot (264)](https://user-images.githubusercontent.com/70102539/161219630-f3006622-87ee-4a4a-a159-6b55d59ad770.png)

Just trying to log in but can't get past that page.

**Comment by jayeclark** [comment]
Hmmm I’ve only personally experienced that hanging screen if I merge new changes or switch  branches without starting & stopping the server… but I know it’s also mentioned in issue #122 so you’re not the only one who has experienced it. 

Have you tried on the ‘live’ dev site? (Paret0.com) Your user info should from the created account should be valid there (sorry for dark mode issues on login, I’ll have a PR open soon to correct.) If it doesn’t work on the live site either that would give me a little more direction to help troubleshoot.

@mikhael28 might have some better trouble shooting ideas but for your local machine mine is limited to ‘have you tried turning it on & off again’? 😂 ( ctrl c in the terminal window where the server is running, and then yarn run start again once it has stopped.)

**Comment by mikhael28** [comment]
@Olaleye-Blessing this is quite confounding - I'm taking a look in Sentry (our error logging software) and it's not returning anything from your session - because there was no error! Can you try this - make a new account, with a different email? I think what might have happened, is that you created a Cognito account - but since you didn't finish making the profile (because the button was disabled due to a bug on our part) you didn't finish making it.

**Comment by jayeclark** [comment]
@mikhael28 I've successfully replicated @Olaleye-Blessing's  issue and your hunch was right -- if you create an account, enter the confirmation code, but don't complete the 'New Student Onboarding' (pictured below), when you try to load the site you get stuck in an endless 'loading' loop that you cannot get out of -- even navigating manually to login/signup or to a nonexistent page doesn't work. Everything is just an endless loading loop, it's not possible to view any content on the site. Restarting the server doesn't help either.
<img width="1312" alt="Screen Shot 2022-04-01 at 11 14 42 AM" src="https://user-images.githubusercontent.com/84106309/161293707-51defac2-de16-4023-bb1a-141c7e2405b6.png">


I was able to solve the issue by deleting the local storage variables related to the site. After doing that, I was able to login -  I never got a prompt to finish the onboarding process, but Pareto has apparently decided that my name is Vilfredo 😂.
<img width="750" alt="Screen Shot 2022-04-01 at 11 18 14 AM" src="https://user-images.githubusercontent.com/84106309/161293305-0673eff6-0833-4c60-b3a5-628eff874cdd.png">
<img width="1058" alt="Screen Shot 2022-04-01 at 11 24 33 AM" src="https://user-images.githubusercontent.com/84106309/161294026-5dc59ad3-782b-4a52-ab4a-2343713114b8.png">

**Comment by Olaleye-Blessing** [comment]
@jayeclark, So should I just follow your solution and see if I could work on this issue?

**Comment by jayeclark** [comment]
@Olaleye-Blessing Yes, that would be fastest (you shouldn't run into the infinite loading issue again I don't think)! 

I believe @mikhael28 is working on a bunch of improvements to how user sessions are managed by the backend but that may take a while.

**Comment by Olaleye-Blessing** [comment]
I followed your advice and I was able to log in. I created a sprint but couldn't find it.

![Screenshot (276)](https://user-images.githubusercontent.com/70102539/161416796-191f9ea0-05a6-4787-9bba-6498a2ed3fd8.png)

I scrolled through the options but couldn't find it.

**Note**:

1. I did this with the previous account I created before I made [this comment](https://github.com/mikhael28/paretOS/issues/158#issuecomment-1085548912).
2. I also noticed that you can only create sprints from Monday to Friday, it's Sunday here. Could it be the reason I'm not seeing it?

**Comment by jayeclark** [comment]
Hmmm, it would still show up if it’s Sunday. 

Is it possible you created a sprint template (a reusable pattern of daily habits to try to achieve) instead of the actual sprint (a event starting on a specific day that uses one of the sprint templates)? 

I just noticed that the button on the template page (in the screenshot) says ‘Create Sprint’ when it should say ‘Create Sprint Template’ - confusing!!

And the section where you actually go to create the sprint is labeled ‘Start a Sprint’ instead of ‘Create a Sprint’…

If you’d like a test account with a couple sprints already set up (and some achievements logged) so you don’t have to navigate a UX that’s still in development, reach out to me at jay@jayeclark.dev & I’ll send some credentials your way. I think I should open a ticket for making some of this labeling clearer (and also adding more tooltips!)

**Comment by Olaleye-Blessing** [comment]
Oh! I'll do so right now.

**Comment by mikhael28** [comment]
Great work Olaleye! I am sending you an invitation to our contributor-only Discord, it's quite an exclusive club.
