### ISSUE TITLE
No more response after signing up

### ISSUE THREAD

**Issue by Olaleye-Blessing** [mikhael28/paretOS#159]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
I was directed to the screenshot below after signing up.

![Screenshot (260)](https://user-images.githubusercontent.com/70102539/161042848-5f6af811-3ee6-43d8-879b-2ad8cfe11512.png)

Nothing happens after clicking the **Create Account** button as you can see in the network tab.

Then I got the screenshot below after refreshing the page.

![Screenshot (261)](https://user-images.githubusercontent.com/70102539/161043173-6d577b1b-1da4-4a94-9a0d-a5096cdefbe2.png)

### Steps to Reproduce

1.  Go to [paret0 sign up page](https://www.paret0.com/signup)
2. Sign up with new Gmail.
3. Enter your confirmation code
4. Fill in the create account details.
5. Click on **Create Account** button.

**Expected behavior:**
Direct to some other page after clicking on **Create Account** button.

**Actual behavior:**
Does nothing after clicking on **Create Account** button.

**Reproduces how often:**
I only tried it once, so I'm not quite sure.

### Others
I saw some links that go to [atom](https://atom.io/) but I don't know how this is related to it

**Comment by jayeclark** [comment]
I didn’t realize the PR to fix this button issue (#152 ) hadn’t been merged yet. I just bumped it now for code review!

**Comment by jayeclark** [comment]
@Olaleye-Blessing I've gone ahead and merged in a fix for this issue. If you fetch & merge the most recent commits from main, you should no longer encounter this bug!

**Comment by mikhael28** [comment]
@Olaleye-Blessing thank you so much for putting this issue together - this helped spur myself and @jayeclark into action! As to the Atom links, that is a part of some GitHub issue/pull-request boilerplate that we added, but should remove lol
