### ISSUE TITLE
Replace Async-Await queues in App.js with Promise.all

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#163]
Right now, in `App.js`, we are initialize the state of the application by fetching some data. For example, in `fetchSanitySchemas` we have three different API requests to fetch items from our sanity dataset - instead of them being three separate API requests that are 'awaited', we can use Promise.all to speed up the process of those requests returning. Please refer to this blog post to see what I mean: https://levelup.gitconnected.com/changing-async-await-to-promises-all-to-speed-up-api-calls-in-node-js-348ea70592fd

This patter can be applied elsewhere, but let's start here - let's bring a slight improvement in our initial fetch performance by converting these await functions to Promise.all!

**Comment by RAnis2017** [comment]
Hi, I got free time this weekend and would like to help you out with this `fetchSanitySchemas`  refactoring issue.
I looked at the function already with three separately awaited calls. Just need your go-ahead.  :)

**Comment by jayeclark** [comment]
That would be awesome @RAnis2017, assigning it to you now!

**Comment by mikhael28** [comment]
Thank you @RAnis2017 !

**Comment by mikhael28** [comment]
This was partially addressed through @RAnis2017 ’s PR on refactoring the sanity API queries into Promise.all - however, there are still other parts of `App.js` that COULD be refactored, however @jayeclark is imminently pushing a PR refactoring App.js into hooks from a class component. Once that PR is reviewed and merged, we will be able to update this issue,

**Comment by jayeclark** [comment]
Yep, I believe my refactor catches all those remaining instances and coverts them to Promise.all!

**Comment by mikhael28** [comment]
Beautiful, closing this issue for now!
