### ISSUE TITLE
Bug?: Material UI TextArea component pulls background color from theme, but does NOT pull input text color from theme

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#166]
## Description

The site was recently converted to a dark mode UI (in preparation for implementing a dark/light toggler.) As part of that process, we encountered an issue with the Material UI TextArea component. I'm not sure if it's a bug or if the documentation is somehow incomplete. It appears that the TextArea background color is pulled from the Material UI theme defined for the site, but the text color of the input is defined independently and does not appear to be able to be altered in the theme. The text color also cannot be altered by passing a style object to the component.

Hopefully someone from the community is able to investigate this and either figure out how to update index text color in the theme, or confirm that it's a bug with Material UI and offer a workaround (this will affect all TextArea input components across the app, which are in the process of being converted from Bootstrap to Material UI, and it would be frustrating to have to do inline or custom class styling on each one of them.)

## Steps to Reproduce

1. Fork, clone, install dependencies, start
2. In your IDE, open the Login component file and remove the inline styling that sets the background color to "#ccc"
3. Save your changes and navigate in the browser to the login page
4. Observe the unreadable input fields and use developer tools to inspect the styles created by Material UI. 

### Expected behavior
Background color should be the "paper" color of the theme; text color should be the primary or secondary text color in the theme

### Actual behavior
Background color is the "paper" color of the theme; text color is black.

### Reproduces how often
Always

### Additional Information
I've implemented a temporary fix via #165 but we'd like to move away from inline styling & CSS overrides. Ideal solutions in order of preference would be:
1. (Best Solution) Changes to Login.js that enable the background & text color to be correctly set by Material ui based on the theme
2. ~~A custom wrapper for the MUI TextField component that can be reused across the app~~ <- after discussion in the contributor discord, the consensus is that this is not desirable. It makes the project less newcomer-friendly & adds unnecessary complexity.
3. A text color or input text color setting in theme object in App.js that can be changed to fix the issue, if this is a problem with Material UI or how we've set up our theme.
4. CSS overrides
5. (Worst solution - not ideal) inline styling

Update: looking at the actual file Login.js, there appear to be some style overrides applied there that I completely missed when reporting this bug. 🤦  Removing the overrides related to color, removing the temporary inline styling, and setting the variant to 'filled' should fix the issue! 

<img width="867" alt="Screen Shot 2022-04-01 at 10 48 00 AM" src="https://user-images.githubusercontent.com/84106309/161287366-dcd3d9bf-6653-49a9-91e3-91b065d40fe0.png">

**Comment by ramachandranram26** [comment]
Hi @jayeclark I have created one new component for the MuiTextFileds and I have overwrite the CSS there, we can use that text  over writed text field all over the application is it Okay ? This is my first open source contribution 🙂 , plz let me know if I wrong . I have attached that out login page screenshot here . 
![image](https://user-images.githubusercontent.com/55104665/161551050-51f6ffcf-b314-4b83-b22a-5ce17ca58383.png)
![useStyles](https://user-images.githubusercontent.com/55104665/161552126-b603324f-aebd-4b9e-bd68-009c0f295b4b.jpg)

**Comment by jayeclark** [comment]
Hey @ramachandranram26 , thanks for the suggestion, much appreciated! However, after discussing with @mikhael28 I don't think we want to create a custom component unless absolutely necessary. I think it is probably _not_ an issue with Material UI - I used the TextField component on another project recently and did not have any issues with the input text or label in dark mode.

Have you verified that the label and input text color being black is actually a bug with Material UI and not some style that has been manually overridden somewhere? (Is there a way to fix the issue just by altering the code in Login.js?)

**Comment by ramachandranram26** [comment]
Hai @jayeclark Yes I can able to fix this issue by altering the code in Login.js file itself , can please assign the task to me 🙂

**Comment by jayeclark** [comment]
Assigned!
