### ISSUE TITLE
Refactor: Replace react-bootstrap Image components with Material UI (Multiple PRs Accepted)

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#168]
## Description

Several files are using Bootstrap Image components - these need to be migrated to Material UI as part of the overall migration away from React-Bootstrap. Please respond with which item(s) in the checklist you'd like to tackle, and I'll assign you & mark them off as claimed!

Material UI does not currently have an Image component, but recommends the third party package `mui-image` (see [https://stackoverflow.com/questions/61263669/does-material-ui-have-an-image-component](https://stackoverflow.com/questions/61263669/does-material-ui-have-an-image-component) )

**Please note:** you will likely need to change both the import AND the props passed to the component when it is actually used. If you are the first person contributing to this issue, you will also need to install mui-image and ensure that it is saved as a dependency in package.json.

Read the `mui-image` docs [here](https://www.npmjs.com/package/mui-image)
Read the React Bootstrap `<Image/>` docs [here](https://react-bootstrap.github.io/components/images/) 

### Claimed
App - claimed by @xeonstaff
LeftNav (used 2x) claimed by @xeonstaff

### Available
- [ ] ArenaDashboard
- [ ] Sprint
- [ ] ContextBuilder 
- [ ] ContextPage 
- [ ] ExperienceModule
- [ ] Athlete
- [ ] MenteeProfile

**Comment by xeonstaff** [comment]
I'd love to tackle this, assign me to whichever 2-3 you think are the most pressing!

**Comment by jayeclark** [comment]
@xeonstaff Excellent! Maybe you could tackle the Image component in App and LeftNav? Then we can point to those as a ‘how to’ example for new contributors who might not be as familiar with Material UI.

**Comment by mikhael28** [comment]
@xeonstaff you still interesting in contributing here?

**Comment by mikhael28** [comment]
Finished this off! Closing
