### ISSUE TITLE
Horizontal Scroll should be prevented 

### ISSUE THREAD

**Issue by Oyedare** [mikhael28/paretOS#170]
I found an horizontal scroll when i opened the live website and it should be worked upon

**Comment by jayeclark** [comment]
Confirmed - I'm seeing slight horizontal scrolls on some pages and big ones on others. Good catch - thank you!!  
![horizontal](https://user-images.githubusercontent.com/84106309/161352616-c9ec114a-5977-4d80-81f6-e3425125371c.gif)

![horizontal2](https://user-images.githubusercontent.com/84106309/161352617-7823bd9b-9d89-406f-9ccf-ad8314e39f11.gif)

**Comment by mikhael28** [comment]
The sprint template creation template is probably the most experimental of the experimental features available right now! Very open to suggestions for redesigning, especially in mobile. Also open to having some sort of 'experimental' mode, where by default stuff like this is hidden - but can be enabled in the profile settings if someone wants to see the latest and greatest. Thank you @Oyedare for recording this! Would you like to take this on?

**Comment by Oyedare** [comment]
I'd love to

**Comment by mikhael28** [comment]
@Oyedare any questions that we can help you with to knock this ticket out?

**Comment by Olaleye-Blessing** [comment]
Can I work on it?

**Comment by mikhael28** [comment]
Yes, @Olaleye-Blessing I'm putting you on it too - maybe you an @Oyedare can meet up in Lagos somewhere and work on it together!

**Comment by Olaleye-Blessing** [comment]
I'm no longer in Lagos🙂
![Screenshot (358)](https://user-images.githubusercontent.com/70102539/163878056-0b0bf4b0-07d7-4b5c-a3ba-04aea546654e.png)

I noticed some pages too like this have this 'unnecessary' horizontal scroll. Should they be removed and shown if necessary?

**Comment by mikhael28** [comment]
Ahh @Olaleye-Blessing makes sense, I just read your GitHub bio and assumed. Probably best to keep it Lagos for the employers :D will review the associated PR tomorrow.

**Comment by mikhael28** [comment]
Alright, closing this issue - great work @Olaleye-Blessing !
