### ISSUE TITLE
Refactor: Migrate react-bootstrap Modal component to Material UI Dialog

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#178]
## Description

There are three instances where the react-bootstrap Modal component is still being used. We're looking to migrate these Material UI as part of a broader initiative to convert to MUI. You're welcome to tackle them all or just one!

React Bootstrap Modal docs: [https://react-bootstrap.github.io/components/modal/](https://react-bootstrap.github.io/components/modal/)
Material UI Dialog docs: https://mui.com/components/dialogs/

(General reminder about migrating components: Remember to double check that any old `react-bootstrap` props are removed and any required `@mui/material` props are added.)

## Files needing updating
- [x] arena/ArenaProofModal - claimed
- [x] learn/ApproveExperienceModal - claimed
- [x] learn/NewSubmitProofModal - claimed

**Comment by xeonstaff** [comment]
hey! I'd love to tackle all 3 of these. I've used Material UI on a few projects.

**Comment by xeonstaff** [comment]
hi, my apologies, but I don't think I can finish this...I've made some apps with material but I can't figure all the app logic out and it seems to difficult for me...I've never made a github contribution and thought I'd try but...I've gotta be more careful with which ones I choose

**Comment by jayeclark** [comment]
No worries @xeonstaff - best of luck in your GitHub journey!

**Comment by jayeclark** [comment]
Closing this issue out, it’s an accidental duplicate of #87

**Comment by mikhael28** [comment]
@xeonstaff feel free to pick a different issue that might be a bit easier! The journey of a thousand miles begins with a single step :)
