### ISSUE TITLE
Refactor: Migrate react-bootstrap Glyphicon component to react-icons (multiple PRs accepted!)

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#179]
## Description

There are a handful of files still using the `react-bootstrap` library `Glyphicon` component instead of react-icons. As part of the effort to eliminate React Bootstrap as a project dependency, we'd love some help migrating instances of `Glyphicon` to use the existing `react-icons` dependency instead.

In general, the goal is to have the replacement icon the same as the original, just use the react-icons library instead (Bootstrap icons should be available in that library.) 

However, if you have strong feelings on the use of a particular icon over the current one, and can explain how your suggestion would improve the accessibility, consistency, and general design aesthetic of the app, your thoughts are most welcome!

React Icons documentation: [https://react-icons.github.io/react-icons/](https://react-icons.github.io/react-icons/)

Already completed: arena/SprintCreation,  components/LoaderButton, learn/ExperienceModule,
profile/editProfile, profile/resetPassword

## Files still needing updates
None at this time!

**Comment by mikhael28** [comment]
Thank you for sending that PR in! Only a few more to go, soon `react-bootstrap` will be consigned to history lol

**Comment by jayeclark** [comment]
These have all been taken care of now!
