### ISSUE TITLE
Utilizing Suspense API

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#18]
In `index.js`, we have a barebones Suspense integration - how can we more effectively utilize this? Take a look at React's documentation: https://reactjs.org/docs/concurrent-mode-suspense.html

We have a few options:
1. Could be used to show placeholder UI components while data is fetching, similar to `Profile` in `src/profile/Profile`.
2. Could we potentially replace the initial loading Modal, with the motivational quotes, with this? We need to gradually display the data in the initial fetch anyway, the motivational loading system is cute but ultimately takes way too long to present data to the users. A lot may be turned off, especially first time users loading things up, and waiting an extra 5 seconds while the lambda's heat up (because we have few to no users, as of 8.28.2021)
3. An integration with React's lazy loading, allowing us to split up our bundle and have smaller initial bundle sizes.

**Comment by vmcodes** [comment]
@mikhael28 this may have been a better issue to label in my pull request, updating now.

**Comment by mikhael28** [comment]
Closing this for now, great work @vmcodes adding lazy loading to our Routing tree!
