### ISSUE TITLE
Chore: refactor CreateUser and EditProfile from a class to a function component

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#189]
## Description
There are still a handful of class components in the codebase that need to be converted to hooks. If you're looking to get more practice with hooks or on refactoring in general, it would be fantastic (and much appreciated) if you could help the project out!

<img width="626" alt="Screen Shot 2022-04-11 at 7 50 19 PM" src="https://user-images.githubusercontent.com/84106309/162851230-73b489a7-a1e3-46af-8355-050569155279.png">

## Files Affected
- [ ] profile/CreateUser
- [ ] profile/EditProfile

These are related components, they have a fair amount of code but it's mostly the render() method, so refactoring them to hooks should be pretty straightforward.  If you're looking for where to find them in the app, the CreateUser component appears when you first sign up (if you *don't* complete the form, it can lead to some weird outcomes right now). The edit profile form is available through the "profile" link in the left navigation bar. You are welcome to convert them to TypeScript as part of the refactor (but it isn't necessary - we can open a second issue about it if not.)

**Comment by Ngoakor12** [comment]
Hey, I'd like to work on this, can you assign me this issue?

**Comment by jayeclark** [comment]
Sure @Ngoakor12 !

**Comment by mikhael28** [comment]
Great work @Ngoakor12 - it was a pleasure reviewing your code. Closing this issue!
