### ISSUE TITLE
Bug(Design): Date picker in "Start a Sprint" is unreadable after the UI update due to white background

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#200]
## Description

We recently made major updates to the UI, including defaulting to a dark mode theme. As a result of this change, the datepicker component on the "Start a Sprint" page is no longer readable. This needs to be fixed so that the datepicker follows the custom Material UI theme defined for the project and will be readable in either dark or light mode.

## Steps to Reproduce
1. Log in to app
2. Navigate to "Start a Sprint"

### Expected behavior
The date picker should follow the material UI theme, with its background color being the paper color of the theme, and the text being the text.primary, text.secondary, or other theme color as appropriate. 

### Actual behavior
Background is white and text is white or gray, making it impossible to read.

### Reproduces how often
Always

### Additional Information
It would be a good idea to first double-check whether the date-picker default styles are being overridden in index.css. When fixing, please make it dependent on the Material UI theme variables (rather than just hard coding the color) -- we will want it to automatically switch to the correct colors when 'light mode' is active!

<img width="1020" alt="Screen Shot 2022-04-16 at 10 30 54 AM" src="https://user-images.githubusercontent.com/84106309/163679330-75fc29ce-f285-4db2-bb54-a142a85db862.png">

**Comment by Ngoakor12** [comment]
Hey @jayeclark, I want to work on this issue, can you assign me please?

**Comment by Ngoakor12** [comment]
The previous date picker was still using the react-calendar library, I replaced it with a mui date picker component. It seems to be dark mode without me need to update anything(see below). I also couldn't find an exact replica of the previous Calendar component, **Should I leave it as is?**

![Screenshot from 2022-04-18 19-43-59](https://user-images.githubusercontent.com/54069197/163850546-fdb8b6b9-9e5a-43e2-9db3-e9c2e9ac068a.png)

**Comment by mikhael28** [comment]
Thank you @Ngoakor12 , your PR was fantastic. Closing this issue!
