### ISSUE TITLE
Chore: index.css has unused classes and also could be better organized

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#201]
## Description
Index.css has gotten fairly disorganized/long and could use a good, thorough review and cleanup!

Eventually, we'd like to split it up to be a bit more modular. Index.css would contain only styles used throughout the project, and the individual css modules would contain groups of styles relevant to a particular component or view.

We can prepare for this eventual migration by organizing index.css into several sections: one main section for broadly used styles, and then additional sections for groups of styles that are relevant to specific components or views. We can also remove unneeded styles (there appear to be several classes that are no longer used in the project.)

## To Do List
- [ ] Classes that are no longer used anywhere in the project should be removed
- [ ] Style overrides for material-ui components should happen in theme rather than in index.css
- [ ] There are some react-bootstrap overrides in index.css, these should be reviewed to confirm that the particular component is still in use. (The repo is migrating to Material UI.) If the component is no longer in use, the CSS override can be removed
- [ ] Use a CSS linter lik stylelint or csslint to fix issues in the organization of the file

## Additional Information
This work should not create changes in the UI. If your work changes the UI, you have gone astray and deleted something you shouldn't have!

**Comment by sumitsaurabh927** [comment]
I want to work on this!

But I'm new to open source development so I might need a little hand-holding.

**Comment by mikhael28** [comment]
@sumitsaurabh927 how about you work on this ticket to start with? It's pretty simple, just replacing react-bootstrap buttons with MUI buttons!

**Comment by MidnightChems** [comment]
Taking a look!

Thanks,

**Comment by MidnightChems** [comment]
Thanks for merging  #235 . 

I'm working on separating the CSS files right now! :smile:

**Comment by mikhael28** [comment]
@MidnightChems any progress to share here? Assigning you this ticket, FYI :)

**Comment by mikhael28** [comment]
Closing, great work @MidnightChems !
