### ISSUE TITLE
CreateUser <form> integration

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#21]
In `src/profile/CreateUser` let's add a <form> html component to wrap the form, so that once all the form fields have been validated, we can use the Enter button to submit the new profile information. This is also good for screen-readers + accessibility.

**Comment by shubhankarb180** [comment]
Hi @mikhael28 ! Can you please elaborate about the HTML component part ? Are talking about semantic tags here ?

**Comment by mikhael28** [comment]
Yes, I'm talking about the semantic <form> tag! Let's add that in to the component - in general, we want to have those in all forms in the codebase, as long as the validate form function allows it.

**Comment by mikhael28** [comment]
For some reason, when you try to write the html tag with the < and > it doesn't show up in GitHub (at least in my mobile app)
