### ISSUE TITLE
Bug: Sprint display date shows the start date instead of the day of the sprint, and date is incorrect

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#210]
## Description

There are two bugs with sprint start date that need to be cleaned up.

On the 'sprint' page (the page to view an individual sprint), the date displayed (in purple) for the current stats page is always the start date of the sprint. However, it should actually display the date of whichever day of the sprint is currently being shown. Each sprint has five days that users can toggle among using 'time travel'. (If the sprint is currently active, the achievements that are shown are for the current day.) The 

In addition, the date that's showing is off by 1 day. A sprint that starts Monday 4/18 is showing up as Tuesday 4/19, and the sprint dates at the very top of the page are also incorrect (showing 4/19 - 4/24 instead of 4/18 - 4/23.)

## Steps to Reproduce

1. Login and create a sprint
2. Note the date of the sprint in the arena sprint views
3. Now click on the sprint and observe the date range in the top header
4. Using time travel, click on different days and complete different numbers of achievements so you can tell the days apart (1 on the first day, 2 on the second, etc.)
5. Now use time travel again and note that the purple date above the achievements does not change no matter which date you click on.

### Expected behavior
- [ ] Purple date header should reflect the date of the achievements being viewed. For example, if you are viewing day 3 of a sprint that started 4/18, the purple header should show as Wednesday, 4/20.
- [ ] Correct sprint start and end dates should be shown. Sprints are 5 days long, so a sprint starting 4/18 should display the date range as 4/18 - 4/23. (Ignore the end dates that show in the 'all sprints' view - they are inaccurate and are another bug that will be getting its own issue.)

### Actual behavior
Purple date header always shows the same date, and is off by a day.
Page header shows the incorrect dates (also off by one day)

### Reproduces how often
Always

### Additional Information
This is how a sprint running from 4/18 - 4/23 and set to show day 3 shows up currently. The header should actually read Sprint 4/18 - 4/23 and the purple subheader should read Wednesday, 4/20
<img width="1005" alt="Screen Shot 2022-04-20 at 9 34 26 AM" src="https://user-images.githubusercontent.com/84106309/164247979-820d8f58-d08f-42f2-9706-471d7540f942.png">

**Comment by jeremydthomas** [comment]
I'll take this one, I've already got the date plus 1 thing fixed, and from what I can tell, the purple date isn't even set up to change currently. Ran out of time last night to figure out how to change it. Came up with an idea already, will implement tonight.

**Comment by jayeclark** [comment]
Fantastic, assigning now! (And yes, you’re correct, the purple date currently is not even set up to change.)

**Comment by mikhael28** [comment]
@jeremydthomas @jayeclark I want to say this has been addressed - closing, but let me know if I'm wrong and we will re-open.
