### ISSUE TITLE
Refactor: Migrate ExperienceSummary to TypeScript

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#211]
## Description
We've started to make some good progress migrating Arena to TypeScript, now let's get to work on the other areas of the app! The "learn" module contains a number of views and components related to getting up to speed as a Full Stack JS developer. (To unlock this module, follow the pay workflow but click on the "no donation" link at the bottom left of the dialog, instead of entering payment information.)

As a first step, we'd like to migrate ExperienceSummary to TypeScript.

## Guidelines
Interfaces that are specific to the functional component and won't need to be used anywhere else should appear in the file immediately before the component declaration itself. The same goes for any subcomponents defined in that file (for files less than 150 lines of code in length, if a subcomponent is ONLY being used by that component, it should stay in that file and not be separated out - for longer files, extracting subcomponents can help with code clarity.)

Interfaces and types that can reasonably be expected to be used by other components (for example, an interface defining a user) should be stored in /types and may already exist in there.

Using 'any' if you're really stuck on a type is OK, but please try to remember to add a TODO to remind us to refine the typing it in the future!

### Additional Information
Screenshot of what the ExperienceSummary component looks like, so you're sure you're working on the right component!
<img width="1302" alt="Screen Shot 2022-04-20 at 10 18 57 AM" src="https://user-images.githubusercontent.com/84106309/164251805-5be38d58-ae26-4509-8866-3c4c1f74668c.png">

**Comment by Olaleye-Blessing** [comment]
I will like to work on this.

**Comment by jayeclark** [comment]
@Olaleye-Blessing Awesome!! Assigning you now.

**Comment by mikhael28** [comment]
Yes, @Olaleye-Blessing that is right - are you still interested in working on this or something more substantial?

**Comment by mikhael28** [comment]
Pretty much our entire codebase is in TypeScript now, though it could likely use better typing here and there - closing this! @Olaleye-Blessing was there anything else you wanted to work on?
