### ISSUE TITLE
Internationalization: Incomplete Spanish translations

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#220]
## Description
The translation work to localize ParetOS into Spanish has only been partially completed. We would love some help finishing the translation so that Spanish language speakers can have an immersive experience! (Also it's quite confusing to select Español as your language and then randomly have certain pages be all in English!) Unfortunately, my Spanish is not quite up to the task.

## Steps to Reproduce

1. Login to app
2. Select Spanish as language
3. Start clicking around the different areas of the app, you'll quickly notice that not all pages are fully in Spanish!

### Expected behavior
Full Spanish translation of site

### Actual behavior
Translation stops about halfway through the dictionary of phrases, leading some 'Spanish' pages to be completely in English.

## Additional Information
The translations are located in src/libs/strings.js ... missing Spanish translations start around line 700.

<img width="996" alt="Screen Shot 2022-04-23 at 7 59 52 PM" src="https://user-images.githubusercontent.com/84106309/164950014-82879498-ee6d-47c4-901b-3c0030291bb5.png">

**Comment by mikhael28** [comment]
Thank you so much @carmelou - we have a contributor only Discord channel where we can talk about the project, would you like to join? Please leave your email here if so, I will send you an invite!

**Comment by mikhael28** [comment]
Errr @carmelou I'm seeing your email as ***@***.**

If you want, you can send me an email to mikhael@hey.com and I can reply to you there.
