### ISSUE TITLE
Country Picker component

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#23]
In `src/profile/CreateUser`, there is a form at the bottom the select which country you live in. As you can see, right now we are manually populating it with options. We need to have a more comprehensive selection, with the standard exclusions (North Korea, Syria, etc) - how should we do this? Should we use an external NPM component? If so, we need to make sure the bundle size contribution is small. Or, should we find a JSON file somewhere that has a list of each country, along with a link/hyper compressed image of each countries flag, and then just population <option> HTML tags to choose from?

I leave the decision to you, but expect to see a breakdown of the bundle size contribution of either solution (or both). Remember that you can run the source-map-explorer by first building a production bundle with `npm run build` and the `npm run analyze`. NPM will usually tell you the bundle size contribution up front either way. Anything more than 20kb starts to get hairy, but I am open to suggestions.

A final consideration is that, for internationalization purposes, we need to keep in mind the 'value' of the <option> component. We currently have 'support' for three languages, would like to add more at some point, and need to make sure that the 'value' of the country, can have some relation to the 'defaultLanguage' profile/Amplify I18n value. This is tricky, and there is wiggle room here.

**Comment by nikhil12377** [comment]
i'd like to work on this.

**Comment by mikhael28** [comment]
That sounds great @nikhil12377 , I will assign this to you!

**Comment by mikhael28** [comment]
Finished by @nikhil12377 , closing!
