### ISSUE TITLE
Bug: When a sprint gets created, the end date that is sent to the db is incorrect

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#232]
## Description
Sprints that are created via the SprintCreation page ("Start a Sprint") have inaccurate end dates. The end date is being set to a certain number of days from today, not a certain number of days from the scheduled start of the sprint.

## Steps to Reproduce
1. Create a sprint several weeks in the future
2. Navigate to the arena dashboard (showing all sprints) and observe the end date.

### Expected behavior:
Sprint end datetime should be the final day of the sprint, 11:59:59 on the fifth day of the sprint (start_date + 4 days).

### Actual behavior:
Sprint end date is today + 5 days.

### Reproduces how often:
Always

### Additional Information
<img width="1214" alt="Screen Shot 2022-05-04 at 11 02 24 AM" src="https://user-images.githubusercontent.com/84106309/166711020-b6ec6f37-030d-4f35-99e6-79716551f8dd.png">

**Comment by PatrickFanella** [comment]
I'm pretty sure I've solved this, but I can't test because I need to be able to log in

**Comment by jayeclark** [comment]
Hey @PatrickFanella , are you having trouble creating an account? Let me know if you’re experiencing a bug so I can raise it as an issue! (AFAIK account creation is working ok. You can always use a throwaway gmail account if you don’t want your real one in the db for some reason!)

**Comment by mikhael28** [comment]
It looks like this issue was successfully merged ! Thank you @PatrickFanella 

We have a private, contributors-only Discord - would you like to join us and talk about what other contributions you can make to the project? Leave your email in a comment here.
