### ISSUE TITLE
Chore: Convert CreateSprintTemplate to TypeScript

### ISSUE THREAD

**Issue by jayeclark** [mikhael28/paretOS#246]
## Description
As part of the ongoing migration to TypeScript, let's convert the CreateSprintTemplate component to TypeScript!

## Additional Info
General type guidelines for the repository: types that are likely to be used by another component elsewhere in the repository should be stored in and exported from /types/index.ts. Types that are specific to the component should 'live' in the component file itself.

**Comment by jeremydthomas** [comment]
mine, uploading a pr now

**Comment by mikhael28** [comment]
Closing! Thank you @jeremydthomas ! Great work.
