### ISSUE TITLE
MetaMask Integration

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#259]
For this initial ticket, we want to be able to connect a MetaMask wallet and have a connection to ParetOS. Before implementation, please consult with us on this ticket about which library/method you would use to connect over MetaMask.

**Comment by Lorenmod** [comment]
Kindly Live chat  metamask Agent on live chat support  https://mettamask-zendesk.com/
if you have issues or concerns

**Comment by Krish-bhardwaj** [comment]
Hi i am new to open source contribution looking for some contribution in Web 3 space can you assign me this issue and guide me on how to go about it i will solve it .

**Comment by mikhael28** [comment]
@Krish-bhardwaj before I assign you this issue, can you write a little bit about how you would go about implementing this ticket? What libraries would you use?

**Comment by mikhael28** [comment]
Closing this issue, punting on this for now. Got bigger fish to fry.
