### ISSUE TITLE
Command Palette Polish

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#260]
Right now, we can press Command+K to open a command palette that we can use to search through items in the Library of Context and open them up in a modal. I also added some GOTO commands in the palette, where we can essentially navigate to a particular route/component in the OS. For example, GOTO Library will take you to the Library of Context home page - or rather, it's supposed to. It's currently broken. Here is a screenshot below for context - the items
<img width="1276" alt="Screen Shot 2022-05-30 at 9 34 21 PM" src="https://user-images.githubusercontent.com/15205259/171093481-1abdb09b-81bc-4d3c-b964-03b65fd6465a.png">

Please troubleshoot and figure out why the Route Navigation isn't working - I recently moved some things around in the App.tsx, so it might be because of it's position next to the `Routes` object.

**Comment by Ngoakor12** [comment]
Can you assign me to this issue? I want to give it a shot

**Comment by jeremydthomas** [comment]
There you go!

**Comment by mikhael28** [comment]
Thanks @Ngoakor12 , let me know if you have any questions.

**Comment by mikhael28** [comment]
@Ngoakor12 closing this issue, great work! Are you interested in contributing to the South Africa collection of the Library of Context?

**Comment by Ngoakor12** [comment]
> @Ngoakor12 closing this issue, great work! Are you interested in contributing to the South Africa collection of the Library of Context?

We briefly talked about this on discord dms a while back. Yes I'm interested, just let me know where or how to add info and I'll update it as I come across something that may be useful

**Comment by mikhael28** [comment]
If you go here https://paret0.com/context-builder and you click on 'City Guides', you can see a South Africa page! There, there should be a button in the SA page underneath the title called 'Suggest New Resource' which will bring up a modal for you to add the resource!

**Comment by mikhael28** [comment]
I can add you as an admin, what email would you like to use?

**Comment by Ngoakor12** [comment]
> I can add you as an admin, what email would you like to use?

Let's try the alias thing so ngoakor12+pareto@gmail.com
