### ISSUE TITLE
Replace `redux` with `redux-toolkit` createStore

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#262]
Look in `index.js` - The `redux` library has an exported function called createStore - however, this has recently been deprecated, with the following message: 
```
@deprecated
We recommend using the configureStore method of the @reduxjs/toolkit package, which replaces createStore.
Redux Toolkit is our recommended approach for writing Redux logic today, including store setup, reducers, data fetching, and more.
For more details, please read this Redux docs page: https://redux.js.org/introduction/why-rtk-is-redux-today
```
Please follow the recommendations of this library, and update the code accordingly. Please run through a Sprint in the arena, which is mostly what we use Redux for, before sending in the PR.

**Comment by aldovandus** [comment]
Hi, i would like to work on this. Can you assign it to me? Thx.

**Comment by aldovandus** [comment]
hi @mikhael28 yes i confirm, thanks!

**Comment by mikhael28** [comment]
That’s great! Let me know if you have any questions, should be relatively straightforward.

**Comment by mikhael28** [comment]
@aldovandus great work here! I've merged in your PR, closing this issue!
