### ISSUE TITLE
Problem signing up

### ISSUE THREAD

**Issue by eddybruv** [mikhael28/paretOS#279]
### Description
I faced an issue when trying to sign up to ParetOS

### Steps to Reproduce

1. Go to the [ParetOS](https://www.paret0.com/) website
2. Choose the signup option
3. Redirects to code confirmation page before actual sign up

**Expected behavior:**

Expected a sign up form.

**Actual behavior:**

Shown a code confirmation input.

**Comment by jayeclark** [comment]
@eddybruv Confirming I'm experiencing this issue too.

**Comment by jayeclark** [comment]
It's a bug that got introduced in the recent TypeScript conversion - could have sworn I'd double checked that route, but apparently not. I appreciate the catch (& fix)!

**Comment by eddybruv** [comment]
I'll submit a PR then

> It's a bug that got introduced in the recent TypeScript conversion - could have sworn I'd double checked that route, but apparently not. I appreciate the catch (& fix)!

**Comment by eddybruv** [comment]
Thanks for merging
