### ISSUE TITLE
ChangePassword - Refactor into Hook

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#28]
Convert this class component into a Hook. Pretty self-explanatory, good first issue.

**Comment by shubhankarb180** [comment]
@mikhael28 I would like to work on this issue. Can you assign the issue please ? I am new to open source contribution but I have worked in some first timers issues and have knowledge on react hooks

**Comment by mikhael28** [comment]
Go ahead and get started! I will figure out how to assign an issue to someone who isn't a 'contributor' on the main repository. Let me know if you have any questions, will look forward to seeing your PR!

**Comment by mikhael28** [comment]
@shubhankarb180 it appears that I can only assign read+write access to collaborators on a private repository, and will have to transfer the repository at some point to a GitHub organization, where I can have more granular access. In order to 'assign' an issue, you must be a listed collaborator on the repository. So, in the meantime, start working on the issue and send in your PR. I will handle the transfer in the next two days, quite busy today outside of code-land.

**Comment by mikhael28** [comment]
Make sure you work on ChangePassword, not ResetPassword - someone just sent in a PR for that one.

**Comment by shubhankarb180** [comment]
Sure @mikhael28 . I will working on ChangePassword component 🙂
