### ISSUE TITLE
Pomodoro Timer - Service Worker Integration

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#29]
Pomodoro Vision - The ParetOS offers you the 20% of software that will give you 80% of the benefits you are looking for. Adding a Pomodoro timer, that in the future we will be able to track over time and apply towards your Arena score, verified by timers, will allow us to serve our Paretoans (or whatever we want to call users,, toans, I just don't like the word 'user'). 

We had previously integrated a Pomodoro timer, thanks to some functional looking boilerplate code that I found somewhere on the internet. And while, at first glance, everything seemed great, when navigating away from the tab, I found that the timer would lag/stop working completely. I figured this had something to do with JavaScripts execution threads, and after some quick Googling - I found I was right! 

The UI for the primary part of the timer is already there, in `src/components/pomodoro`. We already have some good looking Side-nav placement in the desktop view, as you can see it is commented out towards the bottom of App.js. There are a few requirements here:

1. Replace the `setInterval` based timer method with one that takes advantage of Service Worker functionality. Read[ this article](https://hackwild.com/article/web-worker-timers/) for reference and look at this [GitHub repository](https://github.com/splode/worker-timer-demo) for another reference.
2. Refactor into a Hook. If it pleases you, start over from scratch.
3. Have the ability to store a 25 minute work, 5 break, 25 work, 5 break, 25 work, 15 break cycle. Store the timestamps of each of these operations in localStorage. Once the pomodoro has been completed, store it as an object inside of a localStorage array called `pomodoros`. This data will eventually be stored in a database, but for now localStorage will suffice.
4. Create a component that will map through the localStorage `pomodoros` item and display those records in a simple Card view.
5. Maintain/improve the current UI. Will likely need to add a <p> or something below the timer, indicating the current stage of the pomodoro ('Break', 'Work1', 'Work 2', 'Break 2', etc)
6. Add in sounds - a timer alarm that beeps when it's time for break/resume work. Add in browser-based compatibility checks, to make sure certain functionality doesn't break on Safari/Chrome/mobile.

This is an 'ownership' ticket, meaning that completion of this ticket (fully) will qualify you to become a 'core-contributor' of the project. This is an end-to-end piece of functionality, and future functionality/bug fixes/edits for this will be your responsibility as well! Leave questions below!

**Comment by akashshyamdev** [comment]
hey @mikhael28, could I handle this? I haven't worked with service workers before but I intend to learn as I go! Looking forward to hearing from you :)

**Comment by mikhael28** [comment]
@akashshyamdev yes, I can definitely assign this to you. I think working on an 'ownership' ticket is a great idea for you. Keep in mind that this is a piece of functionality with a high degree of functionality, and you will likely be working on this for the next couple of weeks. Multiple code-reviews. And we will first store the Pomodoro's in localStorage, but we will store them in a database before this ticket is 'truly' closed.

**Comment by mikhael28** [comment]
Would it be helpful for you, to have me break down this functionality into multiple tickets - a 'series' of Issues?

**Comment by mikhael28** [comment]
@akashshyamdev I also forgot where you posted this, but in one of the Issues or pull-requests you mentioned something about a UI revamp/redesign. If you have some ideas for how to restructure some of the containers/components, please go ahead and put something together on Figma. Keep in mind that some of your suggestions might be welcomed, while others might be rejected :) If you would like to spend some time on that, please do so - I am very aware that the UX needs some work. Please remember that good UI is not necessarily good UX, and vice-versa.

**Comment by akashshyamdev** [comment]
> @akashshyamdev yes, I can definitely assign this to you. I think working on an 'ownership' ticket is a great idea for you. Keep in mind that this is a piece of functionality with a high degree of functionality, and you will likely be working on this for the next couple of weeks. Multiple code-reviews. And we will first store the Pomodoro's in localStorage, but we will store them in a database before this ticket is 'truly' closed.



> Would it be helpful for you, to have me break down this functionality into multiple tickets - a 'series' of Issues?

Yeah that would be really helpful 👍

**Comment by mikhael28** [comment]
@akashshyamdev please review the first step of the project here: https://github.com/mikhael28/paretOS/issues/105

**Comment by mikhael28** [comment]
@akashshyamdev are you still interested in working on this? If so, let me know here - I also emailed you a link to our contributor-only Discord channel, where we can chat about the project as well.

**Comment by akashshyamdev** [comment]
@mikhael28 Sorry, I'm too busy right now 😭

**Comment by mikhael28** [comment]
All good @akashshyamdev - let's stay in touch!
