### ISSUE TITLE
`LanguageSelector.tsx` react-bootstrap -> react-hook-form migration

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#297]
## Description

There are several areas of the repo that are still using the Bootstrap form components FormGroup, FormControl, ControlLabel, and HelpBlock. These should be migrated to Material UI (FormControl, FormControlLabel, and FormHelperText). In addition, we want to have those components refactored to Hook's from classes (if they aren't already), and to use the `react-hook-form` npm library to improve the performance of our forms. Review this [old Issue](https://github.com/mikhael28/paretOS/issues/8) for more details. You can refer to `Login.js` to see what successful implementation looks like.

If you'd like to help, please respond to this issue!

A comprehensive refresher on Material UI forms: [https://smartdevpreneur.com/every-material-ui-form-component-explained-mui-v5/](https://smartdevpreneur.com/every-material-ui-form-component-explained-mui-v5/)

Official docs:
[FormControl](https://mui.com/api/form-control/#main-content)
[FormControlLabel](https://mui.com/api/form-control-label/#main-content)
[FormHelperText](https://mui.com/api/form-helper-text/)

**Comment by jeremydthomas** [comment]
Im going to work on this tonight
