### ISSUE TITLE
`Signup.tsx` react-bootstrap -> react-hook-form migration

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#298]
## Description

There are several areas of the repo that are still using the Bootstrap form components FormGroup, FormControl, ControlLabel, and HelpBlock. These should be migrated to Material UI (FormControl, FormControlLabel, and FormHelperText). In addition, we want to have those components refactored to Hook's from classes (if they aren't already), and to use the `react-hook-form` npm library to improve the performance of our forms. Review this [old Issue](https://github.com/mikhael28/paretOS/issues/8) for more details. You can refer to `Login.js` to see what successful implementation looks like.

If you'd like to help, please respond to this issue!

A comprehensive refresher on Material UI forms: [https://smartdevpreneur.com/every-material-ui-form-component-explained-mui-v5/](https://smartdevpreneur.com/every-material-ui-form-component-explained-mui-v5/)

Official docs:
[FormControl](https://mui.com/api/form-control/#main-content)
[FormControlLabel](https://mui.com/api/form-control-label/#main-content)
[FormHelperText](https://mui.com/api/form-helper-text/)

**Comment by houssamboudiar** [comment]
I would like to work on that !

**Comment by jeremydthomas** [comment]
@houssamboudiar go ahead, we will get you assigned to it.

**Comment by jeremydthomas** [comment]
@houssamboudiar I cant merge in requests, but Im sure @mikhael28 will get on it soon, however, we do have a contributors only discord if you would like to join. Just leave your email here and Ill invite you.

**Comment by houssamboudiar** [comment]
> @houssamboudiar I cant merge in requests, but Im sure @mikhael28 will get on it soon, however, we do have a contributors only discord if you would like to join. Just leave your email here and Ill invite you.

houssam.boudiar0107@gmail.com

**Comment by jeremydthomas** [comment]
@houssamboudiar just sent you an invite from saucebox11@gmail.com

**Comment by houssamboudiar** [comment]
> @houssamboudiar just sent you an invite from saucebox11@gmail.com
> 

I'm in thanks thomas

**Comment by mikhael28** [comment]
Great work @houssamboudiar ! Closing this issue :)
