### ISSUE TITLE
Error Toast UI

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#30]
I don't know what it is, but I just don't like the errorToast notification UI. Can somebody give some practical suggestions/inspirations for us to rework this?

Edit: the UI looks a little better now with thinner buttons, but still not a great experience.

<img width="1114" alt="Screen Shot 2021-08-28 at 6 02 09 PM" src="https://user-images.githubusercontent.com/15205259/131234795-64642e49-54f8-465c-a90b-eef0c5f7be99.png">

**Comment by shubhankarb180** [comment]
We could create it as a modal where we center the error container with grey blurred background. It would better implementation.

**Comment by mikhael28** [comment]
@shubhankarb180 that sounds great to me. If you can work on this, can you find a way to re-purpose the Modal.js component in src/components? Perhaps we can use it for both the terms of service and this, and we pass in some functions as props, so that it can be used in multiple use cases. Let me know if that makes sense?

**Comment by shubhankarb180** [comment]
Give me sometime . I need to review the code and flow to see how modal.js is being used. Once I figure that out will comment if we can re-purpose it. Sounds good ?

**Comment by mikhael28** [comment]
The modal.js is being used in the Terms of Service component! You can always do global search command + shift + f and search for `components/Modal` to understand where that component is being imported from.

**Comment by shubhankarb180** [comment]
@mikhael28 , just got super busy with work. Will work on this issue on weekend. Sounds good ?

**Comment by mikhael28** [comment]
@shubhankarb180 that sounds good, I'm assigning this ticket to you!

**Comment by shubhankarb180** [comment]
@mikhael28 Can you please reassign the issue to someone else ? I tried to work on it but not successful. Will try to work on other issues

**Comment by mikhael28** [comment]
Okay, that sounds good! Any idea what you want to start with?

**Comment by shubhankarb180** [comment]
I am currently looking at the queue and seeing if anything is pending that I can get started with. Let me check and will surely comment on that. In the mean time, if you find anything you want to assign , please let me know . I actually have been busy with work as I had work on weekend as well so will try and look in the issues queue now

**Comment by mikhael28** [comment]
Perhaps @shubhankarb180 you can help us with localization/internationalization - do you speak any languages fluently apart from English? We have @CoDigo93 working on Brazilian/Portugese right now, as per this ticket: https://github.com/mikhael28/paretOS/issues/63

**Comment by shubhankarb180** [comment]
I speak only english as of now. Have planned to learn one more language but later 😊. But will find one issue to work on .

**Comment by mikhael28** [comment]
@jayeclark I’m going to close this issue, as you have addressed a part of the issue with your previous PR. The ultimate goal, is to replace the `react-toastify` package (which currently takes up 50kb of space in the application bundle) with a piece of functionality in MUI/elsewhere. For now though, I’m closing :)
