### ISSUE TITLE
Make the ParetO icon go back to the home page from the signup page.

### ISSUE THREAD

**Issue by jeremydthomas** [mikhael28/paretOS#306]
Currently there is no way to go back to the home page without hitting back from the sign up page. Go ahead and link the ParetO icon back to the home page.

**Comment by Ngoakor12** [comment]
@mikhael28 @jeremydthomas  This issue has not been addressed. The image in the sign up page is not clickable since it's not wrapped by a link to anywhere.

**Comment by jeremydthomas** [comment]
Odd, I see what you mean. I swore it worked when I tested it. If you want to fix it quick go ahead, or I will later today.

**Comment by Ngoakor12** [comment]
Cool and maybe you should reopen the issue incase it doesn't get addressed soon?

There's also a similar issue with the confirm code page. And the reset password page probably also needs a logo that can lead to the homepage aswell.

**Comment by mikhael28** [comment]
@Ngoakor12 would you mind knocking this one out real quick for us - a quick PR just adding the links to those two places you mentioned?
