### ISSUE TITLE
Bump nanoid from v3.3.4 to 4.0

### ISSUE THREAD

**Issue by jeremydthomas** [mikhael28/paretOS#330]
Nanoid needs to be bumped from v3 to to 4. These are breaking changes, so if  someone could please help us migrate to v4 and test that everything continues to work, that would be awesome!

If you need help, Im sure we can put our heads together and figure it out.

**Comment by mikhael28** [comment]
👍

**Comment by jeremydthomas** [comment]
I can probably do this, looks like v4 no longer supports commonjs though if that matters to you @mikhael28

**Comment by mikhael28** [comment]
Nah, that doesn't matter to us on the front-end :) Yes please, assigning to you!

**Comment by mikhael28** [comment]
Closing! Great work @jeremydthomas
