### ISSUE TITLE
Add an unique key prop to the editProfile component

### ISSUE THREAD

**Issue by jeremydthomas** [mikhael28/paretOS#333]
When going to edit your profile open up a console and you will see this error.
![image](https://user-images.githubusercontent.com/63400531/194813904-b76e4f2b-88e4-4ca5-bc76-612c357c410f.png)

Go ahead and add the key prop.

**Comment by Codefreak69** [comment]
Assign this to me

**Comment by mikhael28** [comment]
@Codefreak69 how ya doing? Seems like it should be relatively simple - make sure you pull the latest changes from main before sending in the PR!

**Comment by MidnightChems** [comment]
@mikhael28 @jeremydthomas  Are either of you two able to duplicate this still? I went to 'Profile' and tried to edit and save my bio and profile pic but I didn't see this error in the console.

**Comment by jeremydthomas** [comment]
@MidnightChems no, someone must have fixed it when they did something else.

**Comment by mikhael28** [comment]
Thanks for closing Jeremy!
