### ISSUE TITLE
Remove the scroll borders on Windows

### ISSUE THREAD

**Issue by jeremydthomas** [mikhael28/paretOS#334]
Help Jay make her app pretty on windows!

![image](https://user-images.githubusercontent.com/63400531/194814600-7096e32a-10e5-4486-bdf8-d8d62d00fb03.png)

For some reason on Windows only, on both chrome and firefox, most of the windows have the visible scroll bars. These do not appear on IOS.

Please find a way to remove these scroll bars.

**Comment by jeyansaran620** [comment]
Hi @jeremydthomas, I have found the fix. Will be raising a PR soon.
Could you assign me for this?
