### ISSUE TITLE
Markdown checkboxes on the bug report issue template not showing corrently/ not related to this project.

### ISSUE THREAD

**Issue by Ngoakor12** [mikhael28/paretOS#361]
The prerequsite part of this bug report issue template seems to be copied from the atom repo.

**Suggestion:** remove the prequisite section **OR** add project related points
:point_down: 

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

**Comment by mikhael28** [comment]
Yes, you are 100% right. Let me see if I can make this change.

**Comment by mikhael28** [comment]
They were copied over - when I first opened up the repo to other contributors, I was looking for some good boilerplate and Atom's seemed to have one of the best.

**Comment by mikhael28** [comment]
Done! Closing - feel free to reopen if it hasn't been fixed for some reason :)
