### ISSUE TITLE
CreateSprint Enhancements

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#46]
There have been some obvious UX flaws in the `CreateSprint` component. Here are the changes that we are requesting in this Issue:
1. When the component mounts, we want to automatically add ourselves to the list of competitors - and then remove ourselves from the list of potential competitors, before updating that state to allow items to choose from.
2. After adding a competitor to the Sprint, before creating/starting it, we want to be able to remove them. So, let's add a little red x or something like that next to each player, and when clicked on, removes them from the list and adds them BACK to the list of possible options.
3. Add some sort of loading animation to the drop-down forms for choosing the template and competitors while they are fetching their data. Perhaps display 'Now Loading' as the initial option, or add a placeholder CSS component.
4. For the form validation, do not allow someone to create a sprint without them having selected a template.

In general, if you have any design suggestions for this page, I am wide open to hearing them/seeing them. If you have any recommendations for feature updates/additions to this page, would love to hear them too.

**Comment by mikhael28** [comment]
Asking @wesley3295 to work on this, is anyone else interested?

**Comment by mikhael28** [comment]
One additional thing I can think of, probably outside the scope of this particular ticket, is that as the list of competitors starts to grow (it's growing quite quickly in the last week), a drop down is not going to be an adequate solution. We will need to have other filtering mechanisms, perhaps a search bar to search through the list?

**Comment by wesley3295** [comment]
So implementing the currentUser into selected competitors wouldn't be difficult. However I feel if would be a lot easier to grab user from Redux global state rather than making a filter function over players in SprintCreation.js. There is an initial state for your profile
![init state](https://user-images.githubusercontent.com/67900324/131615061-8911e834-afca-4f2a-b490-42b13f737f20.png)
 
 Maybe we could set this up to where the currentUser could be stored in global store of Redux.

**Comment by wesley3295** [comment]
What CSS framework are you using in the project it looks like you got a mixture of Bootstrap and Material-ui. I prefer Material ui, but you seem to have a lot of Bootstrap incorporated already. I actually have some components you might be interested in for the future of this app. We could meet over zoom and discuss the future of this app and what short term and long term goals you have for it?

**Comment by wesley3295** [comment]
https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#menu
http://ericgio.github.io/react-bootstrap-typeahead/#basic-example
![dropdown](https://user-images.githubusercontent.com/67900324/131764484-c1089628-2f78-4b2f-ad6e-949f4e974578.png)
![typeahead](https://user-images.githubusercontent.com/67900324/131764487-fffef144-1459-480a-b04f-d535aee1b21c.png)
![devtools](https://user-images.githubusercontent.com/67900324/131764677-0864e11c-a17b-4da9-ab85-c92f894540ae.png)

Using this Typeahead component for the search select and the options are coming out funky anybody got an on what's going on?

**Comment by mikhael28** [comment]
Good morning @wesley3295 - for the search component, can you try using the native HTML search component? Check out this code:
```<div class="wrapper">
  <h1>
    Native HTML Search
  </h1>
  
  <input list="items">
  
  <datalist id="items">
    <option value="Marko Denic">
    <option value="FreeCodeCamp">
    <option value="FreeCodeTools">
    <option value="Web Development">
    <option value="Web Developer">
  </datalist>
</div>```

**Comment by mikhael28** [comment]
Regarding the Typeahead module, are you using a new version of React Bootstrap (the 1.0 version?) If so, that is cool (if that is the route you go), but when you submit the pull-request, can you give an update of how many more kb that npm package is adding to the bundle size? For some more details, read this: https://github.com/mikhael28/paretOS/issues/20

**Comment by mikhael28** [comment]
Regarding meeting on Zoom and talking more about the future plans for this repository, can you meet me during this Meetup that I am hosting? https://www.meetup.com/open-source-js/events/280427207/

**Comment by mikhael28** [comment]
@wesley3295 I'm closing this ticket, you did a great job of addressing things. How is everything going at your first job?

**Comment by mikhael28** [comment]
We now have a contributors-only Discord channel - would you like to join? If so, leave your email when you reply and I will send you an invite.
