### ISSUE TITLE
PaywallModal UI Enhancements

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#49]
The Paywall is a puzzle of sorts - a user can pay myself, the core-contributor of the project and author of 99% of the code+curriculum+open source issues $89 for some amazing educational products, physical and digital.

However, if you can figure out how to change a couple of values in the front-end code-base, you can completely bypass the paywall and create the accounts necessary to access the online curriculum for Full-Stack Development. If you can't figure it out, my view is that you should consider purchasing the products and investing in your education until you CAN figure it out. 

The Paywall Modal has a few enhancements needed from a visual perspective:

1. The Button color needs to be different for the cancel - a red button.
2. On the Purchase form, the header of each form field is centered, but the placeholder text in each form field is aligned left The header of each form field should also be aligned left, in fact the form should be aligned left and not centered.
3. There should be a way to go back/cancel once you click the 'Purchase button'. 
4. If you click outside of the modal, not just clicking Cancel, it should close the modal/redirect you to the home route.

There might be a few more things, but for now this is a great starting point. Lots of these enhancements are small.

**Comment by RajshreeVats** [comment]
new to open source. can I be assigned to do the required enhancement?

**Comment by mikhael28** [comment]
@RajshreeVats that sounds great to me, I have gone ahead and assigned the ticket to you!

**Comment by mikhael28** [comment]
@RajshreeVats hey, another developer has contributed the code necessary for this Issue, so I am closing it! Sorry about that - is there another Issue you would like to work on?

**Comment by RajshreeVats** [comment]
@mikhael28 No Problem, I will go through other issues and pick one for myself. : )
