### ISSUE TITLE
childProps state review

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#5]
We are currently passing a lot of state through React Router, in the form of childProps. While this doesn't have a performance implication, it does balloon the complexity of the state we are passing through - and we have already identified some unused state. Review what is being passed, potentially eliminate what is not needed. Make list for workflows to be migrated into Redux, if proper.

**Comment by jayeclark** [comment]
Mind if I work on this one @mikhael28?

**Comment by mikhael28** [comment]
@jayeclark sounds great - keep me posted. Perhaps we can use the Context API, or at least experiment with it here to see how we feel about using it. While you are working on App.js, if you want to try: convert it from a class to a hook. We don't really use `componentDidUpdate`, so there shouldn't be much of an issue replicating that kind of logic in useEffects - probably the biggest thing is turning `this.state` into a generic `state` object with the same default initial state, and also making sure the websocket connection/ping every 9.5 minutes still goes off.

**Comment by jayeclark** [comment]
Yes, I can definitely do that. (Refactor to use hooks.) I'll probably do them in two separate PRs - refactor to Hooks first, and then clean up state after.

**Comment by mikhael28** [comment]
W00t, thank you for writing up the ticket!

**Comment by jayeclark** [comment]
@mikhael28 Should I close this one? Short of refactoring the entire app to use context (not really necessary IMO), I think these have been simplified as much as they can be!

**Comment by mikhael28** [comment]
Yes, let's close it! I will go ahead and close it for convenience right now :D
