### ISSUE TITLE
NewSubmitProofModal - Refactor to Hook

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#52]
Inside of `src/learn/NewSubmitProofModal` we want to re-factor that into a hook.

**Comment by RajshreeVats** [comment]
new to open source. can I be assigned to this issue?

**Comment by akashshyamdev** [comment]
Can I be assigned to this issue? I have worked with several projects/clients with React JS and I feel this refactor is right up my alley. Let me know! Thanks

**Comment by mikhael28** [comment]
Hi @akashshyamdev , I will go ahead and assign this issue to you!
@RajshreeVats I have assigned another issue to you, go ahead and work on that one :)

**Comment by akashshyamdev** [comment]
Should I delete the branch for this issue(#62) on my local repo?

**Comment by mikhael28** [comment]
@akashshyamdev yes, go ahead and delete that branch. I am going to close this issue!
