### ISSUE TITLE
ExperienceSummary - UI suggestions

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#54]
Can somebody take a look at the ExperienceSummary component, and provide some helpful UI suggestions/inspirations to see how we can improve the look and feel of the component?

**Comment by antonio-b** [comment]
new to open source. can i be assigned this issue?

**Comment by mikhael28** [comment]
@antonio-b hell yeah, it's yours! Let me know if you have any questions.

**Comment by mikhael28** [comment]
I should have included a screenshot of the component, let me know if you have trouble finding it/where it's mounted in the application.

**Comment by antonio-b** [comment]
ok, thanks

**Comment by antonio-b** [comment]
yes, if you can send a screenshot. much appreciated.

**Comment by mikhael28** [comment]
Hey @antonio-b , I've attached a screenshot of the components in question - they are the card blocks on the top. You can log-in to test your changes, temporarily, at `mentorship@platohq.com` with the password `password123`. This is a temporary account I created for a company to review while job-searching, so it will be deleted once I have finished the process with them.
<img width="1141" alt="Screen Shot 2021-09-01 at 10 16 21 AM" src="https://user-images.githubusercontent.com/15205259/131715171-704788d4-ab9a-444a-a695-77ecc8cdc033.png">

**Comment by Visrutha** [comment]
Hi @mikhael28 , I'm interested in designing UI. But I'm kind of new to open source contribution. Can you assign this issue to me? I'll look into the issue and try my best to give suggestions.

**Comment by mikhael28** [comment]
@Visrutha I actually just merged a pull-request from @antonio-b for this Issue, so I'm going to close it. Visrutha, can you take a look and see if there are other tickets you might be interested in?

**Comment by Visrutha** [comment]
Yeah sure. Thanks!
