### ISSUE TITLE
Portugese/Brazilian Localization

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#63]
Adding in the language strings for the UI in Portugese, adding new entries in the `strings.js` file: https://github.com/mikhael28/paretOS/blob/main/src/libs/strings.js

**Comment by CoDigo93** [comment]
I could do that!

**Comment by CoDigo93** [comment]
I can do this for you!

**Comment by mikhael28** [comment]
@CoDigo93 this would be amazing! I'm assigning it to you, let me break down a few of the things that are necessary.
1. In the `strings.js` file, the first file there is called 'en', for English. Let's add another one for 'pg', or whatever code you think is best for portugese. Lines 7-185 are where the bulk of the translation work is, that is really essential. This is the interface language - don't translate past that, because we need to rethink where we store all of that translated copy for the Arena (and for the educational curriculum! I would like to translate that into portugese as well at some point, but it will likely take time and is way way outside the scope of this ticket)
2. In the LeftNav, we need to add an option in the language dropdown, along with a Brazilian flag, to update the language into Portuges. 
3. In the CreateUser and EditProfile component, we need to add an option to set the default language to Portugese!

**Comment by mikhael28** [comment]
What questions do you have for me?

**Comment by CoDigo93** [comment]
So, i have to translate only to 7 until line 185 right? I thought i'd have to translate between 7 and 280 where the ''en'' object finishes.

**Comment by mikhael28** [comment]
Haha you could do that in the future, but let's first start with the most important UX. If you can do the other translations as well, that would be greatly appreciated, but it doesn't have to be right now/for this ticket.

**Comment by CoDigo93** [comment]
Fine! in the future let me know when you need it.

**Comment by mikhael28** [comment]
Looking forward to seeing the PR! Will be amazing have it accessible to Brazilians

**Comment by CoDigo93** [comment]
Hi my friend, almost done! But i have a question. How do you take those flags for the leftNavbar? Did you pay for them?

**Comment by mikhael28** [comment]
Nah, I just found a URL that includes a small country flag, then attached it to an <img /> tag. I'm sure you can find one somewhere. Or, if you want, you can download a tiny version of the flag (30x30 pixels or something), add it to assets folder, and import it manually instead of downloading it from the web each time.

**Comment by CoDigo93** [comment]
Translation is done! But i noticed a weird behavior. After returning from this 3 marked sections, the language of the page turn into english again, only if the selected language is Lugandan or Portuguese, in spanish that doesn't happen. I searched for any different implementation for spanish translation and i didn't find nothing. Do you have any ideia if that behavior derive from the fact that these 2 languages  isn't fully translated yet?

![Captura de ecrã de 2021-09-07 14-49-57](https://user-images.githubusercontent.com/60116310/132389374-62a6e26c-0fa0-4aa0-a51a-849553b7c67a.png)

**Comment by mikhael28** [comment]
That's fantastic that the localization is done! Yes, this is a bug that is known to us, it is documented here: https://github.com/mikhael28/paretOS/issues/31

After you submit your PR for the translation, would you be interested in tackling this issue?

**Comment by CoDigo93** [comment]
> That's fantastic that the localization is done! Yes, this is a bug that is known to us, it is documented here: #31
> 
> After you submit your PR for the translation, would you be interested in tackling this issue?

i'm going to be off for a week maybe, but yeah! If no one take this issue i'll take it

**Comment by mikhael28** [comment]
@CoDigo93 merged into main, was testing our new develop branch CI deployment (found here: https://develop.d2nlf8vt833582.amplifyapp.com/)

Great work again!
