### ISSUE TITLE
SuggestionModal Refactor to Hook + Small UI Fix

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#65]
The SuggestionModal component needs to be refactored into a React Hook, and also needs a few slight UI fixes.

<img width="951" alt="Screen Shot 2021-09-02 at 9 28 21 AM" src="https://user-images.githubusercontent.com/15205259/131881874-9dd379d7-0378-4647-99ab-3363dcc3395b.png">

The header font needs to move a few pixels to the right, it's right by the left border. 
The main issue is doing a little bit of string manipulation. In the screenshot, you can see 'costaRica' - we want to write a string manipulation function that will refactor that into Costa Rica, or if there are three words, into `Name Of Topic' - essentially, we want to take the camelCase object attribute, and turn it into a UI legible word.

Let me know if you have any question. The modal is accessible inside the Library of Context, the 'Document +' icon on the top right inside of a particular context.

**Comment by mikhael28** [comment]
Any other UI enhancements are appreciated!

**Comment by akashshyamdev** [comment]
Can I handle this refactor? Here's a quick snippet of a possible function to implement for the conversion of camel case to sentence case:

```
const text = 'costaRica';
const result = text.replace(/([A-Z])/g, " $1");
const finalResult = result.charAt(0).toUpperCase() + result.slice(1);

// RES: "Costa Rica"
```

**Comment by mikhael28** [comment]
@akashshyamdev that sounds great! I will assign the ticket to you.

**Comment by akashshyamdev** [comment]
Just one thing, I'd suggest increasing the size of the sub heading("please include the link...") to improve the visual hierarchy. According to me, visual hierarchy should go like this:

1. Title("Suggestion for kampala")
2. Sub Heading("Please include the link...")
3. Input Heading("Title", "Description" etc)

Currently, it's more like this:

1. Title("Suggestion for kampala")
2. Input Heading("Title", "Description" etc)
3. Sub Heading("Please include the link...")

**Comment by mikhael28** [comment]
Agreed, the text is certainly too small - your suggestion for the visual hierarchy is spot on, please make the change! I am going to review your other PR in a few minutes, I'm on a boat right now and waiting for it to launch before pulling out my laptop. Hopefully I will have some data out in the Puget Sound!

**Comment by akashshyamdev** [comment]
Should I delete the branch for this issue(#73) on my local/forked repo?

**Comment by mikhael28** [comment]
Yes, go ahead - I am closing this issue!
