### ISSUE TITLE
ContextObject - add iFrame Display

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#66]
In the `ContextObject` component within the Library of Context, we are currently simply opening up a new tab when clicking on a link. This, however, takes us away from the OS - which lessens the value of what we provide, as we are constantly sending people out of the tab (especially when loading as a ProgressiveWebApplication on MacOS, for example). 

What we want to do, is to change the functionality from being an anchor tag, into the following:
1. When clicking/tapping the card media, we are going to open a modal with similar styling/structure as `Modal.js` inside the `components` folder. Simple, and clean.
2. The modal is going to have an iFrame loading that particularly web content. The modal should be responsive, with the iFrame dimensions stretching based on screen size.
3. There should be an easy to see/tap/click button that says 'Close', below the iFrame which closes the modal and unmount the iFrame.

This is a pretty simple ticket, not too much involved!

**Comment by arvinf07** [comment]
I'll take care of this

**Comment by mikhael28** [comment]
And sold, to the gentleman from New York! This will be a good ticket to get familiar with the repository. When you have time, take a look at the list of issues with a tag called 'ownership' - those are more challenging, end to end items, that I think you should pick from to work on. They will involve multiple pieces of functionality, multiple code reviews and more impressive to talk about in interviews.

**Comment by arvinf07** [comment]
Should the modal take up the entire screen or a small part like the form to suggest a new resource?

**Comment by mikhael28** [comment]
Bigger than the form to suggest a new resource, but not the whole screen. Maybe 80% of the screen?

**Comment by mikhael28** [comment]
Hey @arvinf07 how is this going? Any questions for me?

**Comment by arvinf07** [comment]
Yes. I got the modal displaying but most resources prevent the use of
iframes loading their content by passing x-frame options. The only way I
found to get around this is with php. What do you suggest I do?

**Comment by arvinf07** [comment]
I am thinking about going the php file route and see what happens

**Comment by mikhael28** [comment]
Can you give me a little bit more detail about what you mean by 'php' file route?

**Comment by mikhael28** [comment]
That tentatively sounds great, if we can find a workaround that would be awesome. If not, we could perhaps load a default text that says "This website blocks us from accessing their content remotely - click the button below to go directly to their webpage".

**Comment by arvinf07** [comment]
I didn't really dig into it but I saw two people mention it as the only workaround to this issue. Basically create the php file which loads the url and then load the php file inside the iframe.

**Comment by mikhael28** [comment]
Alright, that sounds interesting - I will look forward to seeing the implementation!

**Comment by mikhael28** [comment]
@arvinf07 great work! Loving the integration - how is everything going at IBM? Congratulations on your first job in software!
