### ISSUE TITLE
NotFound UI

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#68]
Right now, we have a container called 'NotFound', which displays if the user somehow navigates to a route that doesn't exist. Here is what it looks like right now. 
<img width="1432" alt="Screen Shot 2021-09-02 at 9 59 47 AM" src="https://user-images.githubusercontent.com/15205259/131886289-0984eea2-9b43-4682-924d-b0cb0d15e5e3.png">

 We want to add a few things:
1. Add the Pareto logo, from the assets folder.
2. Make the component centered, and responsive to multiple screen sizes.
3. Maybe add a joke. Or a game, like in Chrome's offline mode. Or a music player. Or don't - my point is, if you can think of something to make this page POP, let's try it out. Like an Easter egg.

**Comment by akashshyamdev** [comment]
How about adding some of the same quotes we display currently on the loader?  And maybe we could add an interesting lottie animation.

**Comment by mikhael28** [comment]
I think that sounds great! Quotes are great - what does 'lottie' mean?

**Comment by mikhael28** [comment]
<img width="857" alt="Screen Shot 2021-09-03 at 9 50 58 AM" src="https://user-images.githubusercontent.com/15205259/132041027-c922904e-78ba-4dd0-aa43-2b1d0ffcc016.png">
Making some quick changes, going to commit this code with the next PR that has tickets in the next hour or two. Will await your guidance as to what a lottie is - otherwise, we can likely close this Issue if we can't think of anything else (for now)

**Comment by akashshyamdev** [comment]
@mikhael28 lottie is basically an animation platform. People can use after effect animations inside their wbesites. We can easily take some free animation on https://lottiefiles.com/

**Comment by mikhael28** [comment]
This is why I love open-source, I learn something new every day! Didn't know about these Lottie files, very freaking cool. What I'm going to do, is make a separate ticket to source cool Lotties - but I'm going to go ahead and close this ticket, because the bulk of what I wanted to accomplish is done. We have revamped the NotFound component, made it a little cooler, added branding, got the quotes in. Thanks for your input @akashshyamdev , really appreciate it.
