### ISSUE TITLE
Landing.js UI enhancements

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#69]
In the Landing component, we want to do a couple of things.
1. Add a secondary button next to SignUp, called Login.
2. Add a testimonial from yourself about the app or the open-source community.
3. Try to standardize/optimize the CSS a little bit.

**Comment by LeoHimsef** [comment]
Happy I tried this out, still a react novice

**Comment by mikhael28** [comment]
Alright @LeoHimsef , that sounds great! I've gone ahead and assigned the Issue to you :D

**Comment by mikhael28** [comment]
Can you introduce yourself in #17 to the rest of the team? We'd love to learn more about you!
