### ISSUE TITLE
Signup - Refactor Hook

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#7]
In `src/profile/Signup.js`, we want to refactor that component into a hook from a class.

**Comment by palmdaldaniel** [comment]
@Interested in working with this one, may i ?

I am fresh to contributing to os but I know react hooks.

**Comment by mikhael28** [comment]
@palmdaldaniel that sounds great to me! Go ahead and get started, fork the repo, and send the PR when you are ready! I will review the code, ask for changes (if necessary) and merge it in!

**Comment by mikhael28** [comment]
Great work @palmdaldaniel - I'm closing this issue :D
