### ISSUE TITLE
Dashboard.js refactor to Hook

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#70]
Self-explanatory, refactor into Hook.

**Comment by Chris-isCoding** [comment]
Hey @mikhael28 I would be happy to work on this.

**Comment by mikhael28** [comment]
Sounds good, I'm assigning it to you!

**Comment by Chris-isCoding** [comment]
Dashboard was completely reworked in previous commits:

https://github.com/mikhael28/paretOS/commit/af0d6c14396fa7e480870257f5eaec905889c3fa

https://github.com/mikhael28/paretOS/commit/b903f88903c4764327f123e235aaa1f31ab3fe20

**Comment by mikhael28** [comment]
Ahhhh yeah @Chris-isCoding thanks for being flexible here, I recently did re-do some of the work in the Dashboard - I was clearing a few things up on Friday while on a boat, and writing up tickets/cleaning up state. The PR you sent in was great, refactored to Hooks even with a bunch of changes!
