### ISSUE TITLE
Leaderboard Rework

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#75]
Right now, our leaderboard component is minimalist but functional. It will sort the users passed in by score, and highlight yourself with a custom color. The boilerplate code we started from also has support for 'order by Name', which frankly is unnecessary. 

There are a few things we want to implement:
1. Remove the references to 'orderByName' and generally simplify/consolidate the code needed for the component to run.
2. Refactor into a Hook
3. Test how the component handles more than 10 users at once - what if you are ranked number 27 out of 34 - should the leaderboard default to your place in the hierarchy? Probably.
4. Update the UI a bit - add an olympic podium of sorts.
5. This leaderboard needs to be slightly flexible, in that we want to be able to perhaps search for a particular member to see their score - maybe a search box is a good thing.
6. We want to be able to pass some props in to modify the purpose/UI of the leaderboard - it needs to be able to be active in a global competition context, a local context or a industry/vertical context.

We first need to run some multi-player tests on the Arena to make sure functionality is still working as it was - then we can dive into making this the world class leaderboard functionality it should be. Our goal should be to make it extensible, for many different purposes.

This qualifies as an 'ownership' ticket.

**Comment by jayeclark** [comment]
@mikhael28 I can contribute to this issue! I've already refactored the component to be functional/use hooks, and have made some basic UI and functional improvements. Please see draft pull request & let me know if it looks like it's going in the right direction. If so, I will add additional commits to accomplish the other items on the list.

**Comment by mikhael28** [comment]
Hi @jayeclark this looks great - I would definitely encourage you to put together the code for the entire ownership ticket! One thing I would point out, is that I believe there is an indexing bug with the multiplayer leaderboard that was introduced somewhere down the line. Essentially - when you have multiple players in a Sprint, sometimes the wrong player will have their points total updated incorrectly (eg player 2 will get the 10 points player 1 was supposed to get). I believe this issue is originating in `App.js` where the event listener for the websocket is updating the redux state. If you would like to, we can set up a quick call on Zoom (or maybe I can make a discord server) so that I can walk you through some of the finer details. I just started a new job (yay!) so it would have to be outside of 8-4:30pm PST. Let me know if you have any questions!

**Comment by jayeclark** [comment]
@mikhael28 I understand the issue about the scoring - I'll definitely reach out if I have trouble tracking it down, but it sounds very similar to something I had to track down already in a different repository. Since that error is happening before the props get passed to the leaderboard component, I'll focus first on enhancing the leaderboard component (i.e. build the new UI features as if the users & scores passed to the component are correct.) Once I've gotten that initial PR squared away, I can do a separate one addressing the score assignment logic/redux bug, that will probably take a little longer for me to sort out. (It will also keep everything neat & organized for future contributors!)

**Comment by mikhael28** [comment]
That sounds perfect @jayeclark - let me know if there is anything else I can clarify.

**Comment by mikhael28** [comment]
Great work @jayeclark ! Your PR got merged :) check out the details there!
