### ISSUE TITLE
overflow:scroll in left nav bar.  

### ISSUE THREAD

**Issue by antonio-b** [mikhael28/paretOS#76]
![image](https://user-images.githubusercontent.com/53808501/132047419-a3331d26-fea1-41db-b36a-383fb9e1afeb.png)

remove overflow-x and overflow-y properties to give better UI.

**Comment by antonio-b** [comment]
@mikhael28 I will resolve this issue, can i be assigned?

**Comment by mikhael28** [comment]
@antonio-b yes, I will assign you. Can you please pull the latest code from 'main' - I just now revamped a few things about the LeftNav for mentorship/relationships. Can you see if it's been resolved/changed? I updated the CSS, but the overflow is still there.

**Comment by antonio-b** [comment]
Yes, will do.

**Comment by mikhael28** [comment]
Great work, closing!
