### ISSUE TITLE
Form UI Overhaul - Use react-hook-form to limit re-renders

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#8]
The bootstrap form look leaves a few things to be desired - can we get some ideas or inspiration how to update the styling to reflect a modern, unique look?

Either posting screenshots of forms you think are good, or writing some code and posting some screenshots with the accompanying CSS changes is preferred.

Something else to keep in mind, is that we will migrate our Form UI library, likely, at some point to React-Hook-Form. The reason why is pretty simple - it allows for simple validation functions in the future, and the number of re-renders it forces due to state updates is minimal. It is more performant than react-bootstrap, especially on devices that aren't iPhones or Pixels. We want the OS to run decently on cheap, $50-60 BLU phones available on Amazon, that don't even run the full version of Android. Android Go, or whatever, and a key part of that is LIMITING re-renders, especially those that are pointless.

**Comment by mikhael28** [comment]
React Hook Form details: https://react-hook-form.com/

**Comment by mikhael28** [comment]
This PR can be addressed by migrating one form to start with, then we will make tickets for all the other forms as well.

**Comment by vmcodes** [comment]
What are your thoughts about migrating the current forms to Material UI since the library already exists in the project? I wouldn't mind working on the login/registration sections when I have some time.

**Comment by mikhael28** [comment]
Yes, that sounds good @vmcodes - you can actually use Material UI combined with React-Hook-Form! Check this article out for details on implementation, can you start with **just** the Login page? https://seanconnolly.dev/react-hook-form-material-ui

**Comment by mikhael28** [comment]
View their home page for how their performance breaks down very favorably - we want to minimize the number of DOM re-renders, and also add validation. `react-hook-form` is great for that - `yarn add` it to the repository, and let's see how it looks like with the Login page!

**Comment by vmcodes** [comment]
@mikhael28 Awesome, I'll check it out and work on the login page then.

**Comment by mikhael28** [comment]
Great, let me know if you have any questions.
