### ISSUE TITLE
Lottie Animations sourcing

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#81]
@akashshyamdev just informed me about a cool new animation standard. In his words:
```lottie is basically an animation platform. People can use after effect animations inside their wbesites. We can easily take some free animations on https://lottiefiles.com/ which will help our page stand out```

ParetOS's mission is to help develop human potential, to build the 20% of software we need for 80% of the value. Can our community here source some cool animations from their website, if any, that we could possible use somewhere in our UX to help the OS pop and shine?

**Comment by akashshyamdev** [comment]
Here's a nice [confetti animation](https://lottiefiles.com/74680-confetti) which can be displayed when the user successfully completes a challenge or comes first on the leaderboard.

**Comment by mikhael28** [comment]
I’m going to go ahead and close this issue - right now, I do not see a compelling need for animations anywhere (though I do appreciate @akashshyamdev helping us discover the amazing Lottie animation library!)
