### ISSUE TITLE
Arena Proof Modal Refactor to Hooks

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#90]
Migrate from class to hooks, self explanatory.

**Comment by akashshyamdev** [comment]
@mikhael28 can I handle this?

**Comment by mikhael28** [comment]
Yes, assigning to you!

**Comment by akashshyamdev** [comment]
@mikhael28 I think this issue should be closed... is there a reason it's still open?

**Comment by akashshyamdev** [comment]
@mikhael28 can you mark this PR accepted for hacktober fest using the `hacktoberfest-accepted` label?
