### ISSUE TITLE
Reverse order of sprints in `Sprints`

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#91]
Right now, the sprints are being displayed from 0index on, but they need to be reversed to account for the order they were made. Can probably show 'Most recent' on that first index. Can sort by timestamp created.

**Comment by wesley3295** [comment]
![sprint order by createdAt](https://user-images.githubusercontent.com/67900324/132138992-93fa03af-2051-4467-af7f-4c3f0e0e0fd1.png)
![Screenshot 2021-09-05 122606](https://user-images.githubusercontent.com/67900324/132139015-7a06ac39-369e-401f-b2b7-6d1bf5d0e4f8.png)
This look good? I can put it under a pull request?

**Comment by mikhael28** [comment]
Looks great, please send a pull request. I will be reviewing your other pull request soon, thanks for your patience.

**Comment by mikhael28** [comment]
Great work, closing!
