### ISSUE TITLE
Chat updates upon refresh, needs to update immediately 

### ISSUE THREAD

**Issue by wesley3295** [mikhael28/paretOS#95]
Theoretically, we have a subscription to the DynamoDB table, and it should receive messages in real-time. Perhaps that broke somewhere along the line?

Upon entering a new message into chat we should be able to see that chat appear without refreshing the page.

**Comment by mikhael28** [comment]
I can certainly see that new chat enter the page after I press the enter button - you can't?

Would you mind making a gif of your messaging component?

**Comment by mikhael28** [comment]
Thanks for writing up the ticket! It brings me so much joy to see the messaging being used!

**Comment by mikhael28** [comment]
Can you try this - open up localhost:3000 in a tab, and then create another test account and open up localhost:3000 in incognito - can you see if the messages are instantly transmitted that way?

**Comment by wesley3295** [comment]
REFRESH
![5m2xbd](https://user-images.githubusercontent.com/67900324/132258383-ea15e061-55d8-4787-923a-debbfb410f99.gif)
NAVIGATING APP
![5m2xla](https://user-images.githubusercontent.com/67900324/132258433-cf5589dd-816e-4bdd-946b-26770ae82890.gif)
INCOGNITO RIGHT SIDE
![5m2xv7](https://user-images.githubusercontent.com/67900324/132258531-7398f657-6d45-4e68-88a3-f75b8231f4b1.gif)

**Comment by mikhael28** [comment]
@wesley3295 sorry for the delay in reponse, dealing with a few other things. I've gone ahead and assigned this to myself, to do a review tomorrow and verify the bug. Thank you for the GIFs!

**Comment by mikhael28** [comment]
Closing this ticket, as I have removed the messaging/GraphQL API service from the codebase! going to have a messaging platform embedded, but going to do some research on the right way to do it/potentially use a managed service!
